import { joinLines, selectorFromClass } from './utils';

export function generateEquirectFilterHelperFile(): string {
  return joinLines([
    `export interface EquirectFlatCropOptions {`,
    `  cropX: number;`,
    `  cropY: number;`,
    `  cropWidth: number;`,
    `  cropHeight: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}`,
    ``,
    `export function buildEquirectFlatCropFilter(options: EquirectFlatCropOptions): string {`,
    `  const cropX = Math.max(0, Math.round(options.cropX));`,
    `  const cropY = Math.max(0, Math.round(options.cropY));`,
    `  const cropWidth = Math.max(2, Math.round(options.cropWidth));`,
    `  const cropHeight = Math.max(2, Math.round(options.cropHeight));`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return \`crop=\${cropWidth}:\${cropHeight}:\${cropX}:\${cropY},scale=\${outputWidth}:\${outputHeight}\`;`,
    `}`,
    ``,
    `export function buildEquirectRectilinearFilter(options: {`,
    `  yaw: number;`,
    `  pitch: number;`,
    `  roll?: number;`,
    `  horizontalFov: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}): string {`,
    `  const yaw = Number(options.yaw) || 0;`,
    `  const pitch = Number(options.pitch) || 0;`,
    `  const roll = Number(options.roll ?? 0) || 0;`,
    `  const horizontalFov = Math.max(1, Number(options.horizontalFov) || 90);`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return [`,
    `    \`v360=input=equirect:output=rectilinear:yaw=\${yaw}:pitch=\${pitch}:roll=\${roll}:d_fov=\${horizontalFov}\`,`,
    `    \`scale=\${outputWidth}:\${outputHeight}\`,`,
    `  ].join(',');`,
    `}`,
    ``,
    `export function buildEquirectExtractFilter(`,
    `  mode: 'flat-crop' | 'rectilinear',`,
    `  options: EquirectFlatCropOptions & {`,
    `    yaw?: number;`,
    `    pitch?: number;`,
    `    roll?: number;`,
    `    horizontalFov?: number;`,
    `  },`,
    `): string {`,
    `  if (mode === 'rectilinear') {`,
    `    return buildEquirectRectilinearFilter({`,
    `      yaw: options.yaw ?? 0,`,
    `      pitch: options.pitch ?? 0,`,
    `      roll: options.roll ?? 0,`,
    `      horizontalFov: options.horizontalFov ?? 90,`,
    `      outputWidth: options.outputWidth,`,
    `      outputHeight: options.outputHeight,`,
    `    });`,
    `  }`,
    `  return buildEquirectFlatCropFilter(options);`,
    `}`,
    ``,
  ]);
}

export function generateVideoSource(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output, signal } from '@angular/core';`,
    `import type { Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="media-source" [id]="id()">`,
    `      <header class="media-source__header">`,
    `        <h3>{{ label() }}</h3>`,
    `        <span>{{ sourceWidth() }}×{{ sourceHeight() }}</span>`,
    `      </header>`,
    `      <label class="media-source__upload">`,
    `        <input type="file" [accept]="accept()" (change)="onFileChange($event)" />`,
    `        <span>{{ fileName() || 'Choose video file' }}</span>`,
    `      </label>`,
    `      @if (url()) {`,
    `        <p class="media-source__url">URL: {{ url() }}</p>`,
    `      }`,
    `      @if (captureBlob()) {`,
    `        <p class="media-source__capture">Live capture attached</p>`,
    `      }`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  label = input('Video source');`,
    `  accept = input('video/*');`,
    `  url = input('');`,
    `  sourceWidth = input(4096);`,
    `  sourceHeight = input(2048);`,
    `  captureBlob = input<Blob>();`,
    `  fileName = signal('');`,
    `  videoFile = output<File>();`,
    `  metadata = output<Row>();`,
    ``,
    `  onFileChange(event: Event) {`,
    `    const file = (event.target as HTMLInputElement).files?.[0];`,
    `    if (!file) return;`,
    `    this.fileName.set(file.name);`,
    `    this.videoFile.emit(file);`,
    `    this.metadata.emit({`,
    `      name: file.name,`,
    `      sourceWidth: this.sourceWidth(),`,
    `      sourceHeight: this.sourceHeight(),`,
    `      size: file.size,`,
    `    });`,
    `  }`,
    `}`,
    ``,
  ]);
}

export function generateEquirectViewport(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input, output } from '@angular/core';`,
    `import type { Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="media-viewport" [id]="id()">`,
    `      <header class="media-viewport__header">`,
    `        <h3>{{ label() }}</h3>`,
    `        <button type="button" (click)="emitRegion()">Emit crop region</button>`,
    `      </header>`,
    `      <div class="media-viewport__frame">`,
    `        <div class="media-viewport__crop" [style.left]="cropStyle().left" [style.top]="cropStyle().top" [style.width]="cropStyle().width" [style.height]="cropStyle().height"></div>`,
    `      </div>`,
    `      <p class="media-viewport__meta">`,
    `        Crop {{ cropWidth() }}×{{ cropHeight() }} → Output {{ outputWidth() }}×{{ outputHeight() }}`,
    `      </p>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  label = input('Equirect viewport');`,
    `  sourceWidth = input(4096);`,
    `  sourceHeight = input(2048);`,
    `  cropX = input(1508);`,
    `  cropY = input(664);`,
    `  cropWidth = input(1080);`,
    `  cropHeight = input(720);`,
    `  outputWidth = input(720);`,
    `  outputHeight = input(480);`,
    `  cropRegion = output<Row>();`,
    ``,
    `  cropStyle = computed(() => ({`,
    `    left: \`\${(this.cropX() / this.sourceWidth()) * 100}%\`,`,
    `    top: \`\${(this.cropY() / this.sourceHeight()) * 100}%\`,`,
    `    width: \`\${(this.cropWidth() / this.sourceWidth()) * 100}%\`,`,
    `    height: \`\${(this.cropHeight() / this.sourceHeight()) * 100}%\`,`,
    `  }));`,
    ``,
    `  emitRegion() {`,
    `    this.cropRegion.emit({`,
    `      cropX: this.cropX(),`,
    `      cropY: this.cropY(),`,
    `      cropWidth: this.cropWidth(),`,
    `      cropHeight: this.cropHeight(),`,
    `      outputWidth: this.outputWidth(),`,
    `      outputHeight: this.outputHeight(),`,
    `    });`,
    `  }`,
    `}`,
    ``,
  ]);
}

export function generateLiveCapture(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, ElementRef, input, output, signal, viewChild } from '@angular/core';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    @if (!includeInExport()) {`,
    `      <section class="media-capture media-capture--authoring" [id]="id()">`,
    `        <p>{{ label() }} (authoring only — enable includeInExport for runtime capture)</p>`,
    `      </section>`,
    `    } @else {`,
    `      <section class="media-capture" [id]="id()">`,
    `        <header><h3>{{ label() }}</h3></header>`,
    `        <video #videoEl class="media-capture__video" muted playsinline></video>`,
    `        <button type="button" (click)="startCapture()">`,
    `          {{ active() ? 'Camera active' : 'Start camera' }}`,
    `        </button>`,
    `      </section>`,
    `    }`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  label = input('Live capture');`,
    `  includeInExport = input(false);`,
    `  facingMode = input<'user' | 'environment'>('environment');`,
    `  audio = input(true);`,
    `  captureBlob = output<Blob>();`,
    `  previewUrl = output<string>();`,
    `  active = signal(false);`,
    `  videoEl = viewChild<ElementRef<HTMLVideoElement>>('videoEl');`,
    `  private stream: MediaStream | null = null;`,
    ``,
    `  async startCapture() {`,
    `    this.stream = await navigator.mediaDevices.getUserMedia({`,
    `      video: { facingMode: this.facingMode() },`,
    `      audio: this.audio(),`,
    `    });`,
    `    const video = this.videoEl()?.nativeElement;`,
    `    if (video) {`,
    `      video.srcObject = this.stream;`,
    `      await video.play();`,
    `    }`,
    `    this.active.set(true);`,
    `    this.previewUrl.emit('live');`,
    `  }`,
    `}`,
    ``,
  ]);
}

export function generateWasmMediaEquirect(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `/** Requires: npm install @ffmpeg/ffmpeg @ffmpeg/util */`,
    `import { Component, computed, input, output, signal } from '@angular/core';`,
    `import { FFmpeg } from '@ffmpeg/ffmpeg';`,
    `import { fetchFile, toBlobURL } from '@ffmpeg/util';`,
    `import type { Row } from '../types';`,
    `import { buildEquirectExtractFilter } from '../media/equirect-filter';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="wasm-media" [id]="id()">`,
    `      <header class="wasm-media__header">`,
    `        <h3>{{ label() }}</h3>`,
    `        <span>{{ operation() }} → {{ outputFormat() }}</span>`,
    `      </header>`,
    `      @if (filterPreview()) {`,
    `        <code class="wasm-media__filter">{{ filterPreview() }}</code>`,
    `      }`,
    `      @if (showProgress()) {`,
    `        <div class="wasm-media__progress" role="progressbar" [attr.aria-valuenow]="progress()">`,
    `          <span [style.width.%]="progress()"></span>`,
    `        </div>`,
    `      }`,
    `      @if (operation() === 'equirect-extract') {`,
    `        <button type="button" [disabled]="busy() || !inputFile()" (click)="runEquirectExtract()">`,
    `          {{ busy() ? 'Extracting…' : 'Extract subsection' }}`,
    `        </button>`,
    `      } @else {`,
    `        <p class="wasm-media__hint">Wire input file and choose equirect-extract operation.</p>`,
    `      }`,
    `      @if (error()) {`,
    `        <p class="wasm-media__error">{{ error() }}</p>`,
    `      }`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  label = input('Media transcode');`,
    `  operation = input('transcode');`,
    `  extractionMode = input<'flat-crop' | 'rectilinear'>('flat-crop');`,
    `  outputFormat = input('mp4');`,
    `  cropX = input(1508);`,
    `  cropY = input(664);`,
    `  cropWidth = input(1080);`,
    `  cropHeight = input(720);`,
    `  outputWidth = input(720);`,
    `  outputHeight = input(480);`,
    `  yaw = input(0);`,
    `  pitch = input(0);`,
    `  horizontalFov = input(90);`,
    `  showProgress = input(true);`,
    `  inputFile = input<File | Blob>();`,
    `  cropRegion = input<Row>();`,
    `  outputBlob = output<Blob>();`,
    `  progressChange = output<number>();`,
    `  metadata = output<Row[]>();`,
    `  progress = signal(0);`,
    `  busy = signal(false);`,
    `  error = signal<string | null>(null);`,
    `  private ffmpeg: FFmpeg | null = null;`,
    ``,
    `  filterPreview = computed(() =>`,
    `    this.operation() === 'equirect-extract'`,
    `      ? buildEquirectExtractFilter(this.extractionMode(), {`,
    `          ...this.resolveCrop(),`,
    `          yaw: this.yaw(),`,
    `          pitch: this.pitch(),`,
    `          horizontalFov: this.horizontalFov(),`,
    `        })`,
    `      : '',`,
    `  );`,
    ``,
    `  private resolveCrop() {`,
    `    const region = this.cropRegion();`,
    `    return {`,
    `      cropX: Number(region?.cropX ?? this.cropX()),`,
    `      cropY: Number(region?.cropY ?? this.cropY()),`,
    `      cropWidth: Number(region?.cropWidth ?? this.cropWidth()),`,
    `      cropHeight: Number(region?.cropHeight ?? this.cropHeight()),`,
    `      outputWidth: Number(region?.outputWidth ?? this.outputWidth()),`,
    `      outputHeight: Number(region?.outputHeight ?? this.outputHeight()),`,
    `    };`,
    `  }`,
    ``,
    `  private async ensureFfmpeg() {`,
    `    if (this.ffmpeg) return this.ffmpeg;`,
    `    const ffmpeg = new FFmpeg();`,
    `    ffmpeg.on('progress', ({ progress: ratio }) => {`,
    `      const next = Math.round(ratio * 100);`,
    `      this.progress.set(next);`,
    `      this.progressChange.emit(next);`,
    `    });`,
    `    const baseURL = 'https://unpkg.com/@ffmpeg/core@0.12.6/dist/umd';`,
    `    await ffmpeg.load({`,
    `      coreURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.js\`, 'text/javascript'),`,
    `      wasmURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.wasm\`, 'application/wasm'),`,
    `    });`,
    `    this.ffmpeg = ffmpeg;`,
    `    return ffmpeg;`,
    `  }`,
    ``,
    `  async runEquirectExtract() {`,
    `    const file = this.inputFile();`,
    `    if (!file) {`,
    `      this.error.set('Attach a video file before extracting.');`,
    `      return;`,
    `    }`,
    `    this.busy.set(true);`,
    `    this.error.set(null);`,
    `    try {`,
    `      const ffmpeg = await this.ensureFfmpeg();`,
    `      const inputName = 'input.mp4';`,
    `      const outputName = \`output.\${this.outputFormat()}\`;`,
    `      await ffmpeg.writeFile(inputName, await fetchFile(file));`,
    `      const crop = this.resolveCrop();`,
    `      const filter = buildEquirectExtractFilter(this.extractionMode(), {`,
    `        ...crop,`,
    `        yaw: this.yaw(),`,
    `        pitch: this.pitch(),`,
    `        horizontalFov: this.horizontalFov(),`,
    `      });`,
    `      await ffmpeg.exec(['-i', inputName, '-vf', filter, '-c:a', 'copy', outputName]);`,
    `      const data = await ffmpeg.readFile(outputName);`,
    `      const blob = new Blob([data], { type: \`video/\${this.outputFormat()}\` });`,
    `      this.outputBlob.emit(blob);`,
    `      this.metadata.emit([{`,
    `        filter,`,
    `        outputWidth: crop.outputWidth,`,
    `        outputHeight: crop.outputHeight,`,
    `        format: this.outputFormat(),`,
    `      }]);`,
    `    } catch (nextError) {`,
    `      this.error.set(nextError instanceof Error ? nextError.message : 'Extract failed');`,
    `    } finally {`,
    `      this.busy.set(false);`,
    `    }`,
    `  }`,
    `}`,
    ``,
  ]);
}
