// Generated by tools/backend-parity/generate-seeds.mjs — do not edit.
// Source of truth: tools/backend-parity/seed-model.mjs and
// packages/ui-primitives/preview-content.json.

const seed = {
  "roles": [
    {
      "_id": "viewer",
      "id": "viewer",
      "label": "Viewer",
      "permissions": "read:dashboard,export:report",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "editor",
      "id": "editor",
      "label": "Editor",
      "permissions": "read:dashboard,write:data,use:forms",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "admin",
      "id": "admin",
      "label": "Admin",
      "permissions": "manage:people,manage:roles,manage:settings",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "owner",
      "id": "owner",
      "label": "Owner",
      "permissions": "all",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    }
  ],
  "people": [
    {
      "_id": "person-owner",
      "id": "person-owner",
      "email": "owner@rosettadash.test",
      "display_name": "Ada Owner",
      "role_id": "owner",
      "password_hash": "1cac272ae61b640f1d7c8925882de59fc660f11c7bf120011bb31e4fc6ce76f4",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "person-admin",
      "id": "person-admin",
      "email": "admin@rosettadash.test",
      "display_name": "Bo Admin",
      "role_id": "admin",
      "password_hash": "0bafce0930651a2e41b3ddd8baa7a99c19aea2ca90d5d1fdc54462aaad6777a7",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "person-editor",
      "id": "person-editor",
      "email": "editor@rosettadash.test",
      "display_name": "Cy Editor",
      "role_id": "editor",
      "password_hash": "16adf22dd814c88c257c0d50af4842baf0a297e7fe392028de88cd92c61188be",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "person-editor-2",
      "id": "person-editor-2",
      "email": "editor2@rosettadash.test",
      "display_name": "Di Editor",
      "role_id": "editor",
      "password_hash": "f8bcfd75a0d4a3e932f9ffd8820c69e1bfa31aaeeed521b3d858d691f54be06f",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "person-viewer",
      "id": "person-viewer",
      "email": "viewer@rosettadash.test",
      "display_name": "El Viewer",
      "role_id": "viewer",
      "password_hash": "ffbbaae72972030fb702bf414eafdc136c21e3a8329b98dc9961d40a8f1d33d8",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "person-viewer-2",
      "id": "person-viewer-2",
      "email": "viewer2@rosettadash.test",
      "display_name": "Fi Viewer",
      "role_id": "viewer",
      "password_hash": "5a4199ba4fe7dfab45871bbaa8f2624490e13f1789ecc0476b7d21988eec9875",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    }
  ],
  "orders": [
    {
      "_id": "1",
      "id": "1",
      "name": "Globex LLC",
      "status": "Active",
      "amount": 12400,
      "date": "2026-08-07",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "2",
      "id": "2",
      "name": "Initech",
      "status": "Pending",
      "amount": 8900,
      "date": "2026-08-06",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "3",
      "id": "3",
      "name": "Umbrella Co",
      "status": "Review",
      "amount": 15250,
      "date": "2026-08-05",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "4",
      "id": "4",
      "name": "Stark Industries",
      "status": "Closed",
      "amount": 22100,
      "date": "2026-08-04",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "5",
      "id": "5",
      "name": "Wayne Enterprises",
      "status": "Active",
      "amount": 18750,
      "date": "2026-08-03",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "6",
      "id": "6",
      "name": "Hooli",
      "status": "Active",
      "amount": 9600,
      "date": "2026-08-02",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "7",
      "id": "7",
      "name": "Pied Piper",
      "status": "Pending",
      "amount": 4300,
      "date": "2026-08-01",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "8",
      "id": "8",
      "name": "Massive Dynamic",
      "status": "Review",
      "amount": 31500,
      "date": "2026-07-31",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    }
  ],
  "news_articles": [
    {
      "_id": "news-1",
      "id": "news-1",
      "headline": "Global markets react to policy shift",
      "source": "Reuters",
      "region": "Global",
      "published_at": "2026-08-11",
      "summary": "Analysts weigh impacts across sectors as central banks signal coordinated action.",
      "url": "https://example.com/news/1",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "news-2",
      "id": "news-2",
      "headline": "Regional energy grid completes upgrade",
      "source": "AP",
      "region": "North America",
      "published_at": "2026-08-10",
      "summary": "The modernization project improves resilience ahead of peak demand.",
      "url": "https://example.com/news/2",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "news-3",
      "id": "news-3",
      "headline": "Tech consortium publishes open media spec",
      "source": "Bloomberg",
      "region": "Europe",
      "published_at": "2026-08-09",
      "summary": "The draft standard targets interoperable authoring pipelines.",
      "url": "https://example.com/news/3",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    },
    {
      "_id": "news-4",
      "id": "news-4",
      "headline": "Shipping lanes report record throughput",
      "source": "Financial Times",
      "region": "Asia Pacific",
      "published_at": "2026-08-08",
      "summary": "Port operators cite automation and expanded berth capacity.",
      "url": "https://example.com/news/4",
      "client_id": "client-northwind",
      "project_id": "project-revenue",
      "created_at": "2026-08-01T00:00:00Z"
    }
  ]
};

const target = db.getSiblingDB("rosettadash");

for (const [collection, documents] of Object.entries(seed)) {
  target[collection].deleteMany({});
  if (documents.length > 0) {
    target[collection].insertMany(documents);
  }
  print('seeded ' + collection + ': ' + target[collection].countDocuments() + ' document(s)');
}
