-- Generated by tools/backend-parity/generate-seeds.mjs — do not edit.
-- Source of truth: tools/backend-parity/seed-model.mjs and
-- packages/ui-primitives/preview-content.json.

-- PostgREST needs an anonymous role to answer unauthenticated reads,
-- which is how the Supabase promise is exercised locally.
CREATE ROLE web_anon NOLOGIN;
GRANT USAGE ON SCHEMA public TO web_anon;

CREATE TABLE IF NOT EXISTS "roles" (
  "id" TEXT PRIMARY KEY,
  "label" TEXT NOT NULL,
  "permissions" TEXT NOT NULL,
  "client_id" TEXT NOT NULL,
  "project_id" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL
);

INSERT INTO "roles" ("id", "label", "permissions", "client_id", "project_id", "created_at") VALUES
  ('viewer', 'Viewer', 'read:dashboard,export:report', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('editor', 'Editor', 'read:dashboard,write:data,use:forms', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('admin', 'Admin', 'manage:people,manage:roles,manage:settings', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('owner', 'Owner', 'all', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z')
ON CONFLICT ("id") DO NOTHING;

CREATE TABLE IF NOT EXISTS "people" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "role_id" TEXT NOT NULL,
  "password_hash" TEXT NOT NULL,
  "client_id" TEXT NOT NULL,
  "project_id" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL
);

INSERT INTO "people" ("id", "email", "display_name", "role_id", "password_hash", "client_id", "project_id", "created_at") VALUES
  ('person-owner', 'owner@rosettadash.test', 'Ada Owner', 'owner', '1cac272ae61b640f1d7c8925882de59fc660f11c7bf120011bb31e4fc6ce76f4', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('person-admin', 'admin@rosettadash.test', 'Bo Admin', 'admin', '0bafce0930651a2e41b3ddd8baa7a99c19aea2ca90d5d1fdc54462aaad6777a7', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('person-editor', 'editor@rosettadash.test', 'Cy Editor', 'editor', '16adf22dd814c88c257c0d50af4842baf0a297e7fe392028de88cd92c61188be', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('person-editor-2', 'editor2@rosettadash.test', 'Di Editor', 'editor', 'f8bcfd75a0d4a3e932f9ffd8820c69e1bfa31aaeeed521b3d858d691f54be06f', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('person-viewer', 'viewer@rosettadash.test', 'El Viewer', 'viewer', 'ffbbaae72972030fb702bf414eafdc136c21e3a8329b98dc9961d40a8f1d33d8', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('person-viewer-2', 'viewer2@rosettadash.test', 'Fi Viewer', 'viewer', '5a4199ba4fe7dfab45871bbaa8f2624490e13f1789ecc0476b7d21988eec9875', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z')
ON CONFLICT ("id") DO NOTHING;

-- orders: rows sourced from preview-content.json → datasets.orders
CREATE TABLE IF NOT EXISTS "orders" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "amount" INTEGER NOT NULL,
  "date" DATE NOT NULL,
  "client_id" TEXT NOT NULL,
  "project_id" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL
);

INSERT INTO "orders" ("id", "name", "status", "amount", "date", "client_id", "project_id", "created_at") VALUES
  ('1', 'Globex LLC', 'Active', 12400, '2026-08-07', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('2', 'Initech', 'Pending', 8900, '2026-08-06', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('3', 'Umbrella Co', 'Review', 15250, '2026-08-05', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('4', 'Stark Industries', 'Closed', 22100, '2026-08-04', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('5', 'Wayne Enterprises', 'Active', 18750, '2026-08-03', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('6', 'Hooli', 'Active', 9600, '2026-08-02', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('7', 'Pied Piper', 'Pending', 4300, '2026-08-01', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('8', 'Massive Dynamic', 'Review', 31500, '2026-07-31', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z')
ON CONFLICT ("id") DO NOTHING;

-- news_articles: rows sourced from preview-content.json → datasets.news
CREATE TABLE IF NOT EXISTS "news_articles" (
  "id" TEXT PRIMARY KEY,
  "headline" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "region" TEXT NOT NULL,
  "published_at" DATE NOT NULL,
  "summary" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "client_id" TEXT NOT NULL,
  "project_id" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL
);

INSERT INTO "news_articles" ("id", "headline", "source", "region", "published_at", "summary", "url", "client_id", "project_id", "created_at") VALUES
  ('news-1', 'Global markets react to policy shift', 'Reuters', 'Global', '2026-08-11', 'Analysts weigh impacts across sectors as central banks signal coordinated action.', 'https://example.com/news/1', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('news-2', 'Regional energy grid completes upgrade', 'AP', 'North America', '2026-08-10', 'The modernization project improves resilience ahead of peak demand.', 'https://example.com/news/2', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('news-3', 'Tech consortium publishes open media spec', 'Bloomberg', 'Europe', '2026-08-09', 'The draft standard targets interoperable authoring pipelines.', 'https://example.com/news/3', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z'),
  ('news-4', 'Shipping lanes report record throughput', 'Financial Times', 'Asia Pacific', '2026-08-08', 'Port operators cite automation and expanded berth capacity.', 'https://example.com/news/4', 'client-northwind', 'project-revenue', '2026-08-01T00:00:00Z')
ON CONFLICT ("id") DO NOTHING;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO web_anon;

