/**
 * Asserts each generated server container actually serves the seeded rows.
 *
 *   npm run parity:check:servers
 *   node tools/backend-parity/check-servers.mjs --only nest,express
 *
 * The apps under test were emitted by the real exporters (see
 * generate-server-apps.mjs), so a pass here means the generated code compiles,
 * boots, connects to Postgres, and returns the seeded data — not merely that
 * the exporter produced plausible-looking text.
 */

import { PARITY_TABLE, SERVER_PROMISES } from './parity-composites.mjs';
import { buildSeedTables } from './seed-model.mjs';

const onlyArgIndex = process.argv.indexOf('--only');
const only =
  onlyArgIndex >= 0 ? process.argv[onlyArgIndex + 1].split(',').map((s) => s.trim()) : null;

const timeoutArgIndex = process.argv.indexOf('--timeout');
/** Generous default: the containers npm install and compile on first boot. */
const timeoutMs = timeoutArgIndex >= 0 ? Number(process.argv[timeoutArgIndex + 1]) : 180_000;

const expectedRowCount =
  buildSeedTables().find((table) => table.name === PARITY_TABLE)?.rows.length ?? 0;

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Waits for a generated server to come up, since first boot installs deps. */
async function waitForRows(url, deadline) {
  let lastError = 'no attempt made';

  while (Date.now() < deadline) {
    try {
      const response = await fetch(url, { signal: AbortSignal.timeout(5000) });
      if (response.ok) {
        const body = await response.json();
        if (Array.isArray(body)) {
          return { ok: true, rows: body };
        }
        lastError = `expected a JSON array, got ${typeof body}`;
      } else {
        lastError = `HTTP ${response.status}: ${(await response.text()).slice(0, 200)}`;
      }
    } catch (error) {
      lastError = error.message;
    }
    await sleep(3000);
  }

  return { ok: false, reason: lastError };
}

const targets = Object.entries(SERVER_PROMISES)
  .filter(([id]) => (only ? only.includes(id) : true))
  .map(([id, promise]) => ({ id, ...promise }));

console.log('RosettaDash backend parity — server promises');
console.log(
  `  Each app was generated by its exporter and reads the seeded "${PARITY_TABLE}" table.\n`,
);

const failures = [];

for (const target of targets) {
  const url = `http://127.0.0.1:${target.port}/api/${PARITY_TABLE}`;
  const deadline = Date.now() + timeoutMs;
  const result = await waitForRows(url, deadline);

  if (!result.ok) {
    console.log(`  [FAIL] ${target.label.padEnd(8)} ${url}`);
    console.log(`         ${result.reason}`);
    failures.push(`${target.label}: ${result.reason}`);
    continue;
  }

  if (result.rows.length !== expectedRowCount) {
    const detail = `served ${result.rows.length} row(s), expected ${expectedRowCount}`;
    console.log(`  [FAIL] ${target.label.padEnd(8)} ${url}`);
    console.log(`         ${detail}`);
    failures.push(`${target.label}: ${detail}`);
    continue;
  }

  const sample = result.rows[0];
  const hasSeedShape = sample && 'name' in sample && 'amount' in sample;
  if (!hasSeedShape) {
    const detail = `rows do not match the seeded shape: ${JSON.stringify(sample).slice(0, 120)}`;
    console.log(`  [FAIL] ${target.label.padEnd(8)} ${url}`);
    console.log(`         ${detail}`);
    failures.push(`${target.label}: ${detail}`);
    continue;
  }

  console.log(
    `  [PASS] ${target.label.padEnd(8)} ${url} → ${result.rows.length} seeded row(s)`,
  );
}

if (failures.length > 0) {
  console.error(`\n${failures.length} unmet server promise(s):\n`);
  for (const failure of failures) {
    console.error(`  - ${failure}`);
  }
  console.error(
    '\nGenerate and start the apps first:\n' +
      '  npm run parity:generate:live\n' +
      '  npm run parity:servers:up\n' +
      '\nOr one terminal for a live demo:\n' +
      '  npm run parity:stack:proof:react\n' +
      '\nFirst boot installs dependencies inside each container, so allow a few\n' +
      'minutes or raise the window with --timeout <ms>.',
  );
  process.exit(1);
}

console.log(`\nAll ${targets.length} server promise(s) hold: generated code serves seeded rows.`);
