/**
 * Renders the canonical seed model into one init script per database engine.
 *
 *   node tools/backend-parity/generate-seeds.mjs
 *   node tools/backend-parity/generate-seeds.mjs --check
 *
 * Output lands in docker/seed/<engine>/ and is mounted into each container's
 * init directory by docker/compose.backends.yml. Everything here is generated;
 * edit seed-model.mjs or preview-content.json instead.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

import {
  BASE_USER_PASSWORD,
  DB_NAME,
  PARITY_CONNECTIONS,
  SEED_PEOPLE,
  SEED_SCOPE,
  SUPABASE_ANON_KEY,
  SUPABASE_ANON_ROLE,
  buildSeedTables,
  workspaceRoot,
} from './seed-model.mjs';

const checkOnly = process.argv.includes('--check');
const seedRoot = join(workspaceRoot, 'docker', 'seed');

const BANNER = [
  '-- Generated by tools/backend-parity/generate-seeds.mjs — do not edit.',
  '-- Source of truth: tools/backend-parity/seed-model.mjs and',
  '-- packages/ui-primitives/preview-content.json.',
  '',
];

// ---------------------------------------------------------------------------
// value + identifier rendering
// ---------------------------------------------------------------------------

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlValue(value, type) {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  if (type === 'int' || type === 'numeric') {
    return String(value);
  }
  return sqlString(value);
}

function postgresType(type, isPrimaryKey) {
  switch (type) {
    case 'int':
      return 'INTEGER';
    case 'numeric':
      return 'NUMERIC(14,2)';
    case 'date':
      return 'DATE';
    case 'timestamp':
      return 'TIMESTAMPTZ';
    default:
      return isPrimaryKey ? 'TEXT' : 'TEXT';
  }
}

function mysqlType(type, isPrimaryKey) {
  switch (type) {
    case 'int':
      return 'INT';
    case 'numeric':
      return 'DECIMAL(14,2)';
    case 'date':
      return 'DATE';
    case 'timestamp':
      return 'DATETIME';
    default:
      // MySQL cannot index TEXT without a prefix length, so keys stay VARCHAR.
      return isPrimaryKey ? 'VARCHAR(128)' : 'VARCHAR(1024)';
  }
}

// ---------------------------------------------------------------------------
// engine renderers
// ---------------------------------------------------------------------------

function renderPostgresSchema(tables, { includePostgrest }) {
  const lines = [...BANNER];

  if (includePostgrest) {
    lines.push(
      '-- PostgREST needs an anonymous role to answer unauthenticated reads,',
      '-- which is how the Supabase promise is exercised locally.',
      `CREATE ROLE ${SUPABASE_ANON_ROLE} NOLOGIN;`,
      `GRANT USAGE ON SCHEMA public TO ${SUPABASE_ANON_ROLE};`,
      '',
    );
  }

  for (const table of tables) {
    const columns = table.columns.map((column) => {
      const isPk = column.key === table.primaryKey;
      const type = postgresType(column.type, isPk);
      return `  "${column.key}" ${type}${isPk ? ' PRIMARY KEY' : ' NOT NULL'}`;
    });

    if (table.source) {
      lines.push(`-- ${table.name}: rows sourced from ${table.source}`);
    }
    lines.push(`CREATE TABLE IF NOT EXISTS "${table.name}" (`, columns.join(',\n'), ');', '');

    const columnList = table.columns.map((column) => `"${column.key}"`).join(', ');
    const valueRows = table.rows.map((row) => {
      const values = table.columns.map((column) => sqlValue(row[column.key], column.type));
      return `  (${values.join(', ')})`;
    });
    lines.push(
      `INSERT INTO "${table.name}" (${columnList}) VALUES`,
      `${valueRows.join(',\n')}`,
      `ON CONFLICT ("${table.primaryKey}") DO NOTHING;`,
      '',
    );
  }

  if (includePostgrest) {
    lines.push(
      `GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${SUPABASE_ANON_ROLE};`,
      '',
    );
  }

  return `${lines.join('\n')}\n`;
}

function renderMysqlSchema(tables) {
  const lines = [...BANNER, `USE \`${DB_NAME}\`;`, ''];

  for (const table of tables) {
    const columns = table.columns.map((column) => {
      const isPk = column.key === table.primaryKey;
      const type = mysqlType(column.type, isPk);
      return `  \`${column.key}\` ${type}${isPk ? ' NOT NULL' : ' NOT NULL'}`;
    });
    columns.push(`  PRIMARY KEY (\`${table.primaryKey}\`)`);

    if (table.source) {
      lines.push(`-- ${table.name}: rows sourced from ${table.source}`);
    }
    lines.push(
      `CREATE TABLE IF NOT EXISTS \`${table.name}\` (`,
      columns.join(',\n'),
      ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;',
      '',
    );

    const columnList = table.columns.map((column) => `\`${column.key}\``).join(', ');
    const valueRows = table.rows.map((row) => {
      const values = table.columns.map((column) => {
        if (column.type === 'timestamp') {
          // MySQL DATETIME will not take the trailing Z from an ISO string.
          return sqlString(String(row[column.key]).replace('T', ' ').replace('Z', ''));
        }
        return sqlValue(row[column.key], column.type);
      });
      return `  (${values.join(', ')})`;
    });
    lines.push(
      `INSERT IGNORE INTO \`${table.name}\` (${columnList}) VALUES`,
      `${valueRows.join(',\n')};`,
      '',
    );
  }

  return `${lines.join('\n')}\n`;
}

function renderMongoSeed(tables) {
  const payload = Object.fromEntries(
    tables.map((table) => [
      table.collection,
      table.rows.map((row) => ({ _id: row[table.primaryKey], ...row })),
    ]),
  );

  return `// Generated by tools/backend-parity/generate-seeds.mjs — do not edit.
// Source of truth: tools/backend-parity/seed-model.mjs and
// packages/ui-primitives/preview-content.json.

const seed = ${JSON.stringify(payload, null, 2)};

const target = db.getSiblingDB(${JSON.stringify(DB_NAME)});

for (const [collection, documents] of Object.entries(seed)) {
  target[collection].deleteMany({});
  if (documents.length > 0) {
    target[collection].insertMany(documents);
  }
  print('seeded ' + collection + ': ' + target[collection].countDocuments() + ' document(s)');
}
`;
}

// ---------------------------------------------------------------------------
// connection template
// ---------------------------------------------------------------------------

function renderConnectionEnv() {
  return [
    '# Generated by tools/backend-parity/generate-seeds.mjs — do not edit.',
    '# Connection strings for the local parity containers. Dev credentials only.',
    '',
    `DATABASE_URL=${PARITY_CONNECTIONS.postgres}`,
    `MYSQL_URL=${PARITY_CONNECTIONS.mysql}`,
    `MONGODB_URI=${PARITY_CONNECTIONS.mongo}`,
    `SUPABASE_URL=${PARITY_CONNECTIONS.supabase}`,
    `SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}`,
    '',
    `ROSETTADASH_CLIENT_ID=${SEED_SCOPE.clientId}`,
    `ROSETTADASH_PROJECT_ID=${SEED_SCOPE.projectId}`,
    '',
    `# Base users (password for all: ${BASE_USER_PASSWORD})`,
    ...SEED_PEOPLE.map((person) => `#   ${person.roleId.padEnd(6)} ${person.email}`),
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// write
// ---------------------------------------------------------------------------

const tables = buildSeedTables();

const artifacts = [
  ['postgres/001-schema.sql', renderPostgresSchema(tables, { includePostgrest: false })],
  ['mysql/001-schema.sql', renderMysqlSchema(tables)],
  ['mongo/001-seed.js', renderMongoSeed(tables)],
  ['supabase/001-schema.sql', renderPostgresSchema(tables, { includePostgrest: true })],
  ['connection.env', renderConnectionEnv()],
];

let drift = false;

for (const [relativePath, content] of artifacts) {
  const target = join(seedRoot, relativePath);

  if (checkOnly) {
    let current = null;
    try {
      current = readFileSync(target, 'utf-8');
    } catch {
      current = null;
    }
    if (current !== content) {
      drift = true;
      console.error(`drift: ${relative(workspaceRoot, target)}`);
    }
    continue;
  }

  mkdirSync(join(target, '..'), { recursive: true });
  writeFileSync(target, content, 'utf-8');
  console.log(`wrote ${relative(workspaceRoot, target)}`);
}

if (checkOnly) {
  if (drift) {
    console.error(
      '\nSeed artifacts are stale. Run: node tools/backend-parity/generate-seeds.mjs',
    );
    process.exit(1);
  }
  console.log('Seed artifacts are up to date.');
} else {
  const counts = tables.map((table) => `${table.name}=${table.rows.length}`).join(' ');
  console.log(`\nSeeded row counts: ${counts}`);
  console.log(`Supabase anon key: ${SUPABASE_ANON_KEY}`);
}
