import { joinLines } from './utils';

export function generateEquirectFilterHelperFile(): string {
  return joinLines([
    `export interface EquirectFlatCropOptions {`,
    `  cropX: number;`,
    `  cropY: number;`,
    `  cropWidth: number;`,
    `  cropHeight: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}`,
    ``,
    `export function buildEquirectFlatCropFilter(options: EquirectFlatCropOptions): string {`,
    `  const cropX = Math.max(0, Math.round(options.cropX));`,
    `  const cropY = Math.max(0, Math.round(options.cropY));`,
    `  const cropWidth = Math.max(2, Math.round(options.cropWidth));`,
    `  const cropHeight = Math.max(2, Math.round(options.cropHeight));`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return \`crop=\${cropWidth}:\${cropHeight}:\${cropX}:\${cropY},scale=\${outputWidth}:\${outputHeight}\`;`,
    `}`,
    ``,
    `export function buildEquirectRectilinearFilter(options: {`,
    `  yaw: number;`,
    `  pitch: number;`,
    `  roll?: number;`,
    `  horizontalFov: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}): string {`,
    `  const yaw = Number(options.yaw) || 0;`,
    `  const pitch = Number(options.pitch) || 0;`,
    `  const roll = Number(options.roll ?? 0) || 0;`,
    `  const horizontalFov = Math.max(1, Number(options.horizontalFov) || 90);`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return [`,
    `    \`v360=input=equirect:output=rectilinear:yaw=\${yaw}:pitch=\${pitch}:roll=\${roll}:d_fov=\${horizontalFov}\`,`,
    `    \`scale=\${outputWidth}:\${outputHeight}\`,`,
    `  ].join(',');`,
    `}`,
    ``,
    `export function buildEquirectExtractFilter(`,
    `  mode: 'flat-crop' | 'rectilinear',`,
    `  options: EquirectFlatCropOptions & {`,
    `    yaw?: number;`,
    `    pitch?: number;`,
    `    roll?: number;`,
    `    horizontalFov?: number;`,
    `  },`,
    `): string {`,
    `  if (mode === 'rectilinear') {`,
    `    return buildEquirectRectilinearFilter({`,
    `      yaw: options.yaw ?? 0,`,
    `      pitch: options.pitch ?? 0,`,
    `      roll: options.roll ?? 0,`,
    `      horizontalFov: options.horizontalFov ?? 90,`,
    `      outputWidth: options.outputWidth,`,
    `      outputHeight: options.outputHeight,`,
    `    });`,
    `  }`,
    `  return buildEquirectFlatCropFilter(options);`,
    `}`,
    ``,
  ]);
}

export function generateVideoSource(name: string): string {
  return joinLines([
    `<script setup lang="ts">`,
    `import { ref } from 'vue';`,
    `import type { Row } from '../types';`,
    ``,
    `const props = withDefaults(`,
    `  defineProps<{`,
    `    id?: string;`,
    `    label?: string;`,
    `    accept?: string;`,
    `    url?: string;`,
    `    sourceWidth?: number;`,
    `    sourceHeight?: number;`,
    `    captureBlob?: Blob;`,
    `  }>(),`,
    `  { label: 'Video source', accept: 'video/*', url: '', sourceWidth: 4096, sourceHeight: 2048 },`,
    `);`,
    ``,
    `const emit = defineEmits<{`,
    `  videoFile: [file: File];`,
    `  metadata: [row: Row];`,
    `}>();`,
    ``,
    `const fileName = ref('');`,
    ``,
    `function emitFile(file: File) {`,
    `  fileName.value = file.name;`,
    `  emit('videoFile', file);`,
    `  emit('metadata', {`,
    `    name: file.name,`,
    `    sourceWidth: props.sourceWidth,`,
    `    sourceHeight: props.sourceHeight,`,
    `    size: file.size,`,
    `  });`,
    `}`,
    `</script>`,
    ``,
    `<template>`,
    `  <section class="media-source" :id="id">`,
    `    <header class="media-source__header">`,
    `      <h3>{{ label }}</h3>`,
    `      <span>{{ sourceWidth }}×{{ sourceHeight }}</span>`,
    `    </header>`,
    `    <label class="media-source__upload">`,
    `      <input type="file" :accept="accept" @change="(event) => {`,
    `        const file = (event.target as HTMLInputElement).files?.[0];`,
    `        if (file) emitFile(file);`,
    `      }" />`,
    `      <span>{{ fileName || 'Choose video file' }}</span>`,
    `    </label>`,
    `    <p v-if="url" class="media-source__url">URL: {{ url }}</p>`,
    `    <p v-if="captureBlob" class="media-source__capture">Live capture attached</p>`,
    `  </section>`,
    `</template>`,
    ``,
  ]);
}

export function generateEquirectViewport(name: string): string {
  return joinLines([
    `<script setup lang="ts">`,
    `import { computed } from 'vue';`,
    `import type { Row } from '../types';`,
    ``,
    `const props = withDefaults(`,
    `  defineProps<{`,
    `    id?: string;`,
    `    label?: string;`,
    `    sourceWidth?: number;`,
    `    sourceHeight?: number;`,
    `    cropX?: number;`,
    `    cropY?: number;`,
    `    cropWidth?: number;`,
    `    cropHeight?: number;`,
    `    outputWidth?: number;`,
    `    outputHeight?: number;`,
    `  }>(),`,
    `  {`,
    `    label: 'Equirect viewport',`,
    `    sourceWidth: 4096,`,
    `    sourceHeight: 2048,`,
    `    cropX: 1508,`,
    `    cropY: 664,`,
    `    cropWidth: 1080,`,
    `    cropHeight: 720,`,
    `    outputWidth: 720,`,
    `    outputHeight: 480,`,
    `  },`,
    `);`,
    ``,
    `const emit = defineEmits<{ cropRegion: [region: Row] }>();`,
    ``,
    `const cropStyle = computed(() => ({`,
    `  left: \`\${(props.cropX / props.sourceWidth) * 100}%\`,`,
    `  top: \`\${(props.cropY / props.sourceHeight) * 100}%\`,`,
    `  width: \`\${(props.cropWidth / props.sourceWidth) * 100}%\`,`,
    `  height: \`\${(props.cropHeight / props.sourceHeight) * 100}%\`,`,
    `}));`,
    ``,
    `function emitRegion() {`,
    `  emit('cropRegion', {`,
    `    cropX: props.cropX,`,
    `    cropY: props.cropY,`,
    `    cropWidth: props.cropWidth,`,
    `    cropHeight: props.cropHeight,`,
    `    outputWidth: props.outputWidth,`,
    `    outputHeight: props.outputHeight,`,
    `  });`,
    `}`,
    `</script>`,
    ``,
    `<template>`,
    `  <section class="media-viewport" :id="id">`,
    `    <header class="media-viewport__header">`,
    `      <h3>{{ label }}</h3>`,
    `      <button type="button" @click="emitRegion">Emit crop region</button>`,
    `    </header>`,
    `    <div class="media-viewport__frame">`,
    `      <div class="media-viewport__crop" :style="cropStyle" />`,
    `    </div>`,
    `    <p class="media-viewport__meta">`,
    `      Crop {{ cropWidth }}×{{ cropHeight }} → Output {{ outputWidth }}×{{ outputHeight }}`,
    `    </p>`,
    `  </section>`,
    `</template>`,
    ``,
  ]);
}

export function generateLiveCapture(name: string): string {
  return joinLines([
    `<script setup lang="ts">`,
    `import { onUnmounted, ref } from 'vue';`,
    ``,
    `const props = withDefaults(`,
    `  defineProps<{`,
    `    id?: string;`,
    `    label?: string;`,
    `    includeInExport?: boolean;`,
    `    facingMode?: 'user' | 'environment';`,
    `    audio?: boolean;`,
    `  }>(),`,
    `  { label: 'Live capture', includeInExport: false, facingMode: 'environment', audio: true },`,
    `);`,
    ``,
    `const emit = defineEmits<{`,
    `  captureBlob: [blob: Blob];`,
    `  previewUrl: [url: string];`,
    `}>();`,
    ``,
    `const videoRef = ref<HTMLVideoElement | null>(null);`,
    `const active = ref(false);`,
    `let stream: MediaStream | null = null;`,
    ``,
    `onUnmounted(() => {`,
    `  stream?.getTracks().forEach((track) => track.stop());`,
    `});`,
    ``,
    `async function startCapture() {`,
    `  stream = await navigator.mediaDevices.getUserMedia({`,
    `    video: { facingMode: props.facingMode },`,
    `    audio: props.audio,`,
    `  });`,
    `  if (videoRef.value) {`,
    `    videoRef.value.srcObject = stream;`,
    `    await videoRef.value.play();`,
    `  }`,
    `  active.value = true;`,
    `  emit('previewUrl', 'live');`,
    `}`,
    `</script>`,
    ``,
    `<template>`,
    `  <section v-if="!includeInExport" class="media-capture media-capture--authoring" :id="id">`,
    `    <p>{{ label }} (authoring only — enable includeInExport for runtime capture)</p>`,
    `  </section>`,
    `  <section v-else class="media-capture" :id="id">`,
    `    <header><h3>{{ label }}</h3></header>`,
    `    <video ref="videoRef" class="media-capture__video" muted playsinline />`,
    `    <button type="button" @click="startCapture">`,
    `      {{ active ? 'Camera active' : 'Start camera' }}`,
    `    </button>`,
    `  </section>`,
    `</template>`,
    ``,
  ]);
}

export function generateWasmMediaEquirect(name: string): string {
  return joinLines([
    `<script setup lang="ts">`,
    `/** Requires: npm install @ffmpeg/ffmpeg @ffmpeg/util */`,
    `import { computed, ref } from 'vue';`,
    `import { FFmpeg } from '@ffmpeg/ffmpeg';`,
    `import { fetchFile, toBlobURL } from '@ffmpeg/util';`,
    `import type { Row } from '../types';`,
    `import { buildEquirectExtractFilter } from '../media/equirect-filter';`,
    ``,
    `const props = withDefaults(`,
    `  defineProps<{`,
    `    id?: string;`,
    `    label?: string;`,
    `    operation?: string;`,
    `    extractionMode?: 'flat-crop' | 'rectilinear';`,
    `    outputFormat?: string;`,
    `    cropX?: number;`,
    `    cropY?: number;`,
    `    cropWidth?: number;`,
    `    cropHeight?: number;`,
    `    outputWidth?: number;`,
    `    outputHeight?: number;`,
    `    yaw?: number;`,
    `    pitch?: number;`,
    `    horizontalFov?: number;`,
    `    showProgress?: boolean;`,
    `    inputFile?: File | Blob;`,
    `    cropRegion?: Row;`,
    `  }>(),`,
    `  {`,
    `    label: 'Media transcode',`,
    `    operation: 'transcode',`,
    `    extractionMode: 'flat-crop',`,
    `    outputFormat: 'mp4',`,
    `    cropX: 1508,`,
    `    cropY: 664,`,
    `    cropWidth: 1080,`,
    `    cropHeight: 720,`,
    `    outputWidth: 720,`,
    `    outputHeight: 480,`,
    `    yaw: 0,`,
    `    pitch: 0,`,
    `    horizontalFov: 90,`,
    `    showProgress: true,`,
    `  },`,
    `);`,
    ``,
    `const emit = defineEmits<{`,
    `  outputBlob: [blob: Blob];`,
    `  progress: [value: number];`,
    `  metadata: [rows: Row[]];`,
    `}>();`,
    ``,
    `const ffmpeg = ref<FFmpeg | null>(null);`,
    `const progress = ref(0);`,
    `const busy = ref(false);`,
    `const error = ref<string | null>(null);`,
    ``,
    `function resolveCrop() {`,
    `  return {`,
    `    cropX: Number(props.cropRegion?.cropX ?? props.cropX),`,
    `    cropY: Number(props.cropRegion?.cropY ?? props.cropY),`,
    `    cropWidth: Number(props.cropRegion?.cropWidth ?? props.cropWidth),`,
    `    cropHeight: Number(props.cropRegion?.cropHeight ?? props.cropHeight),`,
    `    outputWidth: Number(props.cropRegion?.outputWidth ?? props.outputWidth),`,
    `    outputHeight: Number(props.cropRegion?.outputHeight ?? props.outputHeight),`,
    `  };`,
    `}`,
    ``,
    `async function ensureFfmpeg() {`,
    `  if (ffmpeg.value) return ffmpeg.value;`,
    `  const instance = new FFmpeg();`,
    `  instance.on('progress', ({ progress: ratio }) => {`,
    `    const next = Math.round(ratio * 100);`,
    `    progress.value = next;`,
    `    emit('progress', next);`,
    `  });`,
    `  const baseURL = 'https://unpkg.com/@ffmpeg/core@0.12.6/dist/umd';`,
    `  await instance.load({`,
    `    coreURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.js\`, 'text/javascript'),`,
    `    wasmURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.wasm\`, 'application/wasm'),`,
    `  });`,
    `  ffmpeg.value = instance;`,
    `  return instance;`,
    `}`,
    ``,
    `async function runEquirectExtract() {`,
    `  if (!props.inputFile) {`,
    `    error.value = 'Attach a video file before extracting.';`,
    `    return;`,
    `  }`,
    `  busy.value = true;`,
    `  error.value = null;`,
    `  try {`,
    `    const instance = await ensureFfmpeg();`,
    `    const inputName = 'input.mp4';`,
    `    const outputName = \`output.\${props.outputFormat}\`;`,
    `    await instance.writeFile(inputName, await fetchFile(props.inputFile));`,
    `    const crop = resolveCrop();`,
    `    const filter = buildEquirectExtractFilter(props.extractionMode, {`,
    `      ...crop,`,
    `      yaw: props.yaw,`,
    `      pitch: props.pitch,`,
    `      horizontalFov: props.horizontalFov,`,
    `    });`,
    `    await instance.exec(['-i', inputName, '-vf', filter, '-c:a', 'copy', outputName]);`,
    `    const data = await instance.readFile(outputName);`,
    `    const blob = new Blob([data], { type: \`video/\${props.outputFormat}\` });`,
    `    emit('outputBlob', blob);`,
    `    emit('metadata', [{`,
    `      filter,`,
    `      outputWidth: crop.outputWidth,`,
    `      outputHeight: crop.outputHeight,`,
    `      format: props.outputFormat,`,
    `    }]);`,
    `  } catch (nextError) {`,
    `    error.value = nextError instanceof Error ? nextError.message : 'Extract failed';`,
    `  } finally {`,
    `    busy.value = false;`,
    `  }`,
    `}`,
    ``,
    `const filterPreview = computed(() =>`,
    `  props.operation === 'equirect-extract'`,
    `    ? buildEquirectExtractFilter(props.extractionMode, {`,
    `        ...resolveCrop(),`,
    `        yaw: props.yaw,`,
    `        pitch: props.pitch,`,
    `        horizontalFov: props.horizontalFov,`,
    `      })`,
    `    : '',`,
    `);`,
    `</script>`,
    ``,
    `<template>`,
    `  <section class="wasm-media" :id="id">`,
    `    <header class="wasm-media__header">`,
    `      <h3>{{ label }}</h3>`,
    `      <span>{{ operation }} → {{ outputFormat }}</span>`,
    `    </header>`,
    `    <code v-if="filterPreview" class="wasm-media__filter">{{ filterPreview }}</code>`,
    `    <div v-if="showProgress" class="wasm-media__progress" role="progressbar" :aria-valuenow="progress">`,
    `      <span :style="{ width: \`\${progress}%\` }" />`,
    `    </div>`,
    `    <button`,
    `      v-if="operation === 'equirect-extract'"`,
    `      type="button"`,
    `      :disabled="busy || !inputFile"`,
    `      @click="runEquirectExtract"`,
    `    >`,
    `      {{ busy ? 'Extracting…' : 'Extract subsection' }}`,
    `    </button>`,
    `    <p v-else class="wasm-media__hint">Wire input file and choose equirect-extract operation.</p>`,
    `    <p v-if="error" class="wasm-media__error">{{ error }}</p>`,
    `  </section>`,
    `</template>`,
    ``,
  ]);
}
