export * from './link-list/index.js';
export * from './display/index.js';
export * from './media/index.js';
export * from './input/text/index.js';
export * from './input/select/index.js';
export * from './input/number/index.js';
export * from './input/checkbox/index.js';
export * from './input/textarea/index.js';
export * from './input/date-range/index.js';
export * from './table/index.js';
export * from './detail/index.js';
export * from './kpi/index.js';
export * from './skeleton/index.js';
export * from './chart/line/index.js';
export * from './chart/bar/index.js';
export * from './chart/pie/index.js';
export * from './news/language-select/index.js';
export * from './news/region-select/index.js';
export * from './news/type-select/index.js';
export * from './news/search-box/index.js';
export * from './news/results-table/index.js';
export * from './news/article-detail/index.js';
export * from './plugin/status-badge/index.js';
export * from './plugin/metric-chip/index.js';
export * from './display/3d-bar-chart/index.js';
export * from './display/3d-scatter/index.js';
export * from './display/3d-scene/index.js';
export * from './display/3d-gltf-model/index.js';
export * from './display/3d-geo-globe/index.js';
export * from './svg/inline/index.js';
export * from './svg/icon/index.js';
export * from './wasm/worker-host/index.js';
export * from './wasm/module/index.js';

import { registerVisualLinkList } from './link-list/index.js';
import { registerRosettaDashDisplayElements } from './display/index.js';
import { registerRosettaDashMediaElements } from './media/index.js';
import { registerRdTextInput } from './input/text/index.js';
import { registerRdSelectInput } from './input/select/index.js';
import { registerRdNumberInput } from './input/number/index.js';
import { registerRdCheckboxInput } from './input/checkbox/index.js';
import { registerRdTextareaInput } from './input/textarea/index.js';
import { registerRdDateRangeFilter } from './input/date-range/index.js';
import { registerRdDataTable } from './table/index.js';
import { registerRdDetailPanel } from './detail/index.js';
import { registerRdKpiCard } from './kpi/index.js';
import { registerRdLoadingSkeleton } from './skeleton/index.js';
import { registerRdLineChart } from './chart/line/index.js';
import { registerRdBarChart } from './chart/bar/index.js';
import { registerRdPieChart } from './chart/pie/index.js';
import { registerRdNewsLanguageSelect } from './news/language-select/index.js';
import { registerRdNewsRegionSelect } from './news/region-select/index.js';
import { registerRdNewsTypeSelect } from './news/type-select/index.js';
import { registerRdNewsSearchBox } from './news/search-box/index.js';
import { registerRdNewsResultsTable } from './news/results-table/index.js';
import { registerRdNewsArticleDetail } from './news/article-detail/index.js';
import { registerRdStatusBadge } from './plugin/status-badge/index.js';
import { registerRdMetricChip } from './plugin/metric-chip/index.js';
import { registerRdThreeBarChart } from './display/3d-bar-chart/index.js';
import { registerRdThreeScatterPlot } from './display/3d-scatter/index.js';
import { registerRdThreeScenePointCloud } from './display/3d-scene/index.js';
import { registerRdThreeGltfModel } from './display/3d-gltf-model/index.js';
import { registerRdThreeGeoGlobe } from './display/3d-geo-globe/index.js';
import { registerRdSvgInline } from './svg/inline/index.js';
import { registerRdSvgIcon } from './svg/icon/index.js';
import { registerRdWasmWorkerHost } from './wasm/worker-host/index.js';
import { registerRdWasmModule } from './wasm/module/index.js';

export function registerRosettaDashVisualElements(): void {
  registerVisualLinkList();
  registerRosettaDashDisplayElements();
  registerRosettaDashMediaElements();
  registerRdTextInput();
  registerRdSelectInput();
  registerRdNumberInput();
  registerRdCheckboxInput();
  registerRdTextareaInput();
  registerRdDateRangeFilter();
  registerRdDataTable();
  registerRdDetailPanel();
  registerRdKpiCard();
  registerRdLoadingSkeleton();
  registerRdLineChart();
  registerRdBarChart();
  registerRdPieChart();
  registerRdNewsLanguageSelect();
  registerRdNewsRegionSelect();
  registerRdNewsTypeSelect();
  registerRdNewsSearchBox();
  registerRdNewsResultsTable();
  registerRdNewsArticleDetail();
  registerRdStatusBadge();
  registerRdMetricChip();
  registerRdThreeBarChart();
  registerRdThreeScatterPlot();
  registerRdThreeScenePointCloud();
  registerRdThreeGltfModel();
  registerRdThreeGeoGlobe();
  registerRdSvgInline();
  registerRdSvgIcon();
  registerRdWasmWorkerHost();
  registerRdWasmModule();
}
