import type { IRComponent } from '@rosettadash/core';
import { SvelteExportError } from './types';
import {
  generateEquirectViewport,
  generateLiveCapture,
  generateVideoSource,
  generateWasmMediaEquirect,
} from './media-component-templates';
import {
  generateThreeBarChart,
  generateThreeScatterPlot,
  generateThreeScenePointCloud,
  generateThreeGltfModel,
  generateThreeGeoGlobe,
} from './three-visual-templates';
import { joinLines } from './utils';

const SUPPORTED_TYPES = new Set([
  'visual.input.text',
  'visual.input.select',
  'visual.input.number',
  'visual.input.checkbox',
  'visual.input.textarea',
  'visual.input.date-range',
  'domain.time-preset',
  'visual.table',
  'visual.detail',
  'visual.skeleton',
  'visual.kpi',
  'visual.chart.line',
  'visual.chart.bar',
  'visual.chart.pie',
  'visual.display.3d-bar-chart',
  'visual.display.3d-scatter',
  'visual.display.3d-scene',
  'visual.display.3d-gltf-model',
  'visual.display.3d-geo-globe',
  'visual.svg.inline',
  'visual.svg.icon',
  'infra.wasm.asset',
  'visual.wasm.worker-host',
  'visual.wasm.module',
  'visual.wasm.media',
  'visual.media.video-source',
  'visual.media.equirect-viewport',
  'visual.media.live-capture',
  'domain.role-gate',
  'domain.person-invite',
  'domain.role-assign',
  'logic.timer',
  'visual.news.language-select',
  'visual.news.region-select',
  'visual.news.type-select',
  'visual.news.search-box',
  'visual.news.results-table',
  'visual.news.article-detail',
]);

export function generateComponentFile(component: IRComponent, exportName: string): string {
  if (!SUPPORTED_TYPES.has(component.type)) {
    throw new SvelteExportError(`Unsupported Svelte export component type: ${component.type}`);
  }

  switch (component.type) {
    case 'visual.input.text':
      return generateTextInput();
    case 'visual.input.select':
      return generateSelectInput();
    case 'visual.input.number':
      return generateNumberInput();
    case 'visual.input.checkbox':
      return generateCheckboxInput();
    case 'visual.input.textarea':
      return generateTextareaInput();
    case 'visual.input.date-range':
      return generateDateRangeFilter();
    case 'domain.time-preset':
      return generateTimePreset();
    case 'visual.table':
      return generateDataTable();
    case 'visual.detail':
      return generateDetailPanel();
    case 'visual.skeleton':
      return generateSkeleton();
    case 'visual.kpi':
      return generateKpiCard();
    case 'visual.chart.line':
      return generateLineChart();
    case 'visual.chart.bar':
      return generateBarChart();
    case 'visual.chart.pie':
      return generatePieChart();
    case 'visual.display.3d-bar-chart':
      return generateThreeBarChart();
    case 'visual.display.3d-scatter':
      return generateThreeScatterPlot();
    case 'visual.display.3d-scene':
      return generateThreeScenePointCloud();
    case 'visual.display.3d-gltf-model':
      return generateThreeGltfModel();
    case 'visual.display.3d-geo-globe':
      return generateThreeGeoGlobe();
    case 'visual.svg.inline':
      return generateSvgInline();
    case 'visual.svg.icon':
      return generateSvgIcon();
    case 'infra.wasm.asset':
      return generateWasmAsset();
    case 'visual.wasm.worker-host':
      return generateWasmWorkerHost();
    case 'visual.wasm.module':
      return generateWasmModule();
    case 'visual.wasm.media':
      return component.properties?.['operation'] === 'equirect-extract'
        ? generateWasmMediaEquirect()
        : generateWasmMedia();
    case 'visual.media.video-source':
      return generateVideoSource();
    case 'visual.media.equirect-viewport':
      return generateEquirectViewport();
    case 'visual.media.live-capture':
      return generateLiveCapture();
    case 'domain.role-gate':
      return generateRoleGate();
    case 'domain.person-invite':
      return generatePersonInvite();
    case 'domain.role-assign':
      return generateRoleAssign();
    case 'logic.timer':
      return generateTimer();
    case 'visual.news.language-select':
    case 'visual.news.region-select':
    case 'visual.news.type-select':
      return generateSelectInput();
    case 'visual.news.search-box':
      return generateTextInput();
    case 'visual.news.results-table':
      return generateDataTable();
    case 'visual.news.article-detail':
      return generateDetailPanel();
    default:
      throw new SvelteExportError(`Missing Svelte template for ${component.type}`);
  }
}

function generateTextInput(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    placeholder,`,
    `    required = false,`,
    `    value = $bindable(''),`,
    `  }: {`,
    `    id?: string;`,
    `    placeholder?: string;`,
    `    required?: boolean;`,
    `    value?: string;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<label class="field" for={id}>`,
    `  <input class="input" type="text" {id} {placeholder} {required} bind:value />`,
    `</label>`,
    ``,
  ]);
}

function generateNumberInput(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    placeholder = 'enter placeholder here',`,
    `    required = false,`,
    `    min,`,
    `    max = 100,`,
    `    step = 1,`,
    `    value = $bindable(0),`,
    `  }: {`,
    `    id?: string;`,
    `    placeholder?: string;`,
    `    required?: boolean;`,
    `    min?: number;`,
    `    max?: number;`,
    `    step?: number;`,
    `    value?: number;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<label class="field" for={id}>`,
    `  <input class="input" type="number" {id} {placeholder} {required} {min} {max} {step} bind:value />`,
    `</label>`,
    ``,
  ]);
}

function generateCheckboxInput(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    label = '',`,
    `    defaultChecked = false,`,
    `    value = $bindable(defaultChecked),`,
    `  }: {`,
    `    id?: string;`,
    `    label?: string;`,
    `    defaultChecked?: boolean;`,
    `    value?: boolean;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<label class="field field--checkbox" for={id}>`,
    `  <input class="checkbox" type="checkbox" {id} bind:checked={value} />`,
    `  {#if label}`,
    `    <span>{label}</span>`,
    `  {/if}`,
    `</label>`,
    ``,
  ]);
}

function generateTextareaInput(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    placeholder = 'enter placeholder here',`,
    `    required = false,`,
    `    rows = 4,`,
    `    value = $bindable(''),`,
    `  }: {`,
    `    id?: string;`,
    `    placeholder?: string;`,
    `    required?: boolean;`,
    `    rows?: number;`,
    `    value?: string;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<label class="field" for={id}>`,
    `  <textarea class="textarea" {id} {placeholder} {required} {rows} bind:value></textarea>`,
    `</label>`,
    ``,
  ]);
}

function generateSelectInput(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    placeholder = 'Select…',`,
    `    options = [] as Row[],`,
    `    value = $bindable(''),`,
    `  }: {`,
    `    id?: string;`,
    `    placeholder?: string;`,
    `    options?: Row[];`,
    `    value?: string;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<label class="field" for={id}>`,
    `  <select class="select" {id} bind:value>`,
    `    <option value="">{placeholder}</option>`,
    `    {#each options as option, index (String(option.id ?? index))}`,
    `      <option value={String(option.id ?? option.label ?? index)}>`,
    `        {option.label ?? option.id ?? index}`,
    `      </option>`,
    `    {/each}`,
    `  </select>`,
    `</label>`,
    ``,
  ]);
}

function generateDateRangeFilter(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange } from '../types';`,
    `  let {`,
    `    id,`,
    `    preset = 'last-7-days',`,
    `    range = $bindable<DateRange>(),`,
    `  }: {`,
    `    id?: string;`,
    `    preset?: string;`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const current = $derived(range ?? defaultRangeForPreset(preset));`,
    ``,
    `  function onStartChange(start: string) {`,
    `    range = { ...current, start };`,
    `  }`,
    ``,
    `  function onEndChange(end: string) {`,
    `    range = { ...current, end };`,
    `  }`,
    ``,
    `  function defaultRangeForPreset(value: string): DateRange {`,
    `    const end = new Date();`,
    `    const start = new Date(end);`,
    `    if (value === 'last-30-days') start.setDate(end.getDate() - 30);`,
    `    else if (value === 'qtd') start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `    else start.setDate(end.getDate() - 7);`,
    `    return { start: formatDate(start), end: formatDate(end) };`,
    `  }`,
    ``,
    `  function formatDate(date: Date): string {`,
    `    return date.toISOString().slice(0, 10);`,
    `  }`,
    `</script>`,
    ``,
    `<div class="date-range" {id}>`,
    `  <label class="field">`,
    `    <span>Start</span>`,
    `    <input`,
    `      class="input"`,
    `      type="date"`,
    `      value={current.start}`,
    `      oninput={(event) => onStartChange((event.currentTarget as HTMLInputElement).value)}`,
    `    />`,
    `  </label>`,
    `  <label class="field">`,
    `    <span>End</span>`,
    `    <input`,
    `      class="input"`,
    `      type="date"`,
    `      value={current.end}`,
    `      oninput={(event) => onEndChange((event.currentTarget as HTMLInputElement).value)}`,
    `    />`,
    `  </label>`,
    `</div>`,
    ``,
  ]);
}

function generateTimePreset(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange } from '../types';`,
    `  let {`,
    `    id,`,
    `    label = 'Period',`,
    `    defaultPreset = 'last-7-days',`,
    `    range = $bindable<DateRange>(),`,
    `  }: {`,
    `    id?: string;`,
    `    label?: string;`,
    `    defaultPreset?: string;`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const presets = [`,
    `    { id: 'last-7-days', label: 'Last 7 days' },`,
    `    { id: 'last-30-days', label: 'Last 30 days' },`,
    `    { id: 'qtd', label: 'Quarter to date' },`,
    `  ] as const;`,
    ``,
    `  let activePreset = $state<string | null>(null);`,
    ``,
    `  function isActive(preset: string) {`,
    `    return (activePreset ?? defaultPreset) === preset;`,
    `  }`,
    ``,
    `  function selectPreset(preset: string) {`,
    `    activePreset = preset;`,
    `    range = defaultRangeForPreset(preset);`,
    `  }`,
    ``,
    `  function defaultRangeForPreset(value: string): DateRange {`,
    `    const end = new Date();`,
    `    const start = new Date(end);`,
    `    if (value === 'last-30-days') start.setDate(end.getDate() - 30);`,
    `    else if (value === 'qtd') start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `    else start.setDate(end.getDate() - 7);`,
    `    return { start: formatDate(start), end: formatDate(end) };`,
    `  }`,
    ``,
    `  function formatDate(date: Date): string {`,
    `    return date.toISOString().slice(0, 10);`,
    `  }`,
    `</script>`,
    ``,
    `<div class="time-preset" {id}>`,
    `  <span class="time-preset__label">{label}</span>`,
    `  <div class="time-preset__buttons">`,
    `    {#each presets as preset (preset.id)}`,
    `      <button`,
    `        type="button"`,
    `        class="time-preset__button"`,
    `        class:time-preset__button--active={isActive(preset.id)}`,
    `        onclick={() => selectPreset(preset.id)}`,
    `      >`,
    `        {preset.label}`,
    `      </button>`,
    `    {/each}`,
    `  </div>`,
    `</div>`,
    ``,
  ]);
}

function generateDataTable(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange, Row } from '../types';`,
    `  import { isNumericFieldKey } from '../presentation/numeric-fields';`,
    `  let {`,
    `    id,`,
    `    data = [] as Row[],`,
    `    filter,`,
    `    pageSize = 25,`,
    `    sortable = true,`,
    `    filterable = true,`,
    `    selectedRow,`,
    `    onSelectRow,`,
    `  }: {`,
    `    id?: string;`,
    `    data?: Row[];`,
    `    filter?: DateRange;`,
    `    pageSize?: number;`,
    `    sortable?: boolean;`,
    `    filterable?: boolean;`,
    `    selectedRow?: Row;`,
    `    onSelectRow?: (row: Row) => void;`,
    `  } = $props();`,
    ``,
    `  const rows = $derived(filterRows(data, filter).slice(0, pageSize));`,
    `  const columns = $derived.by(() => {`,
    `    const first = rows[0];`,
    `    return first ? Object.keys(first) : ['id', 'label', 'value'];`,
    `  });`,
    ``,
    `  function filterRows(source: Row[], value?: DateRange): Row[] {`,
    `    if (!value) return source;`,
    `    return source.filter((row) => {`,
    `      const dateValue = String(row.date ?? row.createdAt ?? '');`,
    `      if (!dateValue) return true;`,
    `      return dateValue >= value.start && dateValue <= value.end;`,
    `    });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="table-card" {id} data-sortable={sortable} data-filterable={filterable}>`,
    `  <table class="table">`,
    `    <thead>`,
    `      <tr>`,
    `        {#each columns as column (column)}`,
    `          <th class:table-cell--numeric={isNumericFieldKey(column)}>{column}</th>`,
    `        {/each}`,
    `      </tr>`,
    `    </thead>`,
    `    <tbody>`,
    `      {#each rows as row, index (String(row.id ?? index))}`,
    `        <tr`,
    `          class={selectedRow?.id === row.id ? 'table-row table-row--selected' : 'table-row'}`,
    `          onclick={() => onSelectRow?.(row)}`,
    `        >`,
    `          {#each columns as column (column)}`,
    `            <td class:table-cell--numeric={isNumericFieldKey(column)}>{row[column] ?? ''}</td>`,
    `          {/each}`,
    `        </tr>`,
    `      {/each}`,
    `    </tbody>`,
    `  </table>`,
    `</section>`,
    ``,
  ]);
}

function generateDetailPanel(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { Row } from '../types';`,
    `  import { isNumericFieldKey } from '../presentation/numeric-fields';`,
    `  let {`,
    `    id,`,
    `    title = 'Details',`,
    `    emptyMessage = 'Select a row to view details',`,
    `    row,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    emptyMessage?: string;`,
    `    row?: Row;`,
    `  } = $props();`,
    ``,
    `  const fields = $derived.by(() => {`,
    `    if (!row) return [] as Array<{ key: string; value: string }>;`,
    `    return Object.entries(row).map(([key, value]) => ({`,
    `      key,`,
    `      value: String(value ?? ''),`,
    `    }));`,
    `  });`,
    `</script>`,
    ``,
    `<section class="detail-panel" {id}>`,
    `  <h3>{title}</h3>`,
    `  {#if fields.length === 0}`,
    `    <p class="detail-panel__empty">{emptyMessage}</p>`,
    `  {:else}`,
    `    <dl class="detail-panel__fields">`,
    `      {#each fields as field (field.key)}`,
    `        <div class="detail-panel__field">`,
    `          <dt>{field.key}</dt>`,
    `          <dd class:detail-panel__value--numeric={isNumericFieldKey(field.key)}>{field.value}</dd>`,
    `        </div>`,
    `      {/each}`,
    `    </dl>`,
    `  {/if}`,
    `</section>`,
    ``,
  ]);
}

function generateSkeleton(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    loading = true,`,
    `    variant = 'table' as 'table' | 'chart' | 'kpi' | 'card',`,
    `    lines = 4,`,
    `  }: {`,
    `    id?: string;`,
    `    loading?: boolean;`,
    `    variant?: 'table' | 'chart' | 'kpi' | 'card';`,
    `    lines?: number;`,
    `  } = $props();`,
    ``,
    `  const lineIndexes = $derived.by(() => {`,
    `    const count = Math.max(1, Math.min(lines, 8));`,
    `    return Array.from({ length: count }, (_, index) => index);`,
    `  });`,
    `</script>`,
    ``,
    `{#if loading}`,
    `  <div class="skeleton skeleton--{variant}" {id} aria-busy="true">`,
    `    {#if variant === 'chart'}`,
    `      <div class="skeleton__chart-block"></div>`,
    `      <div class="skeleton__legend">`,
    `        {#each lineIndexes as line (line)}`,
    `          <span class="skeleton__line skeleton__line--short"></span>`,
    `        {/each}`,
    `      </div>`,
    `    {:else if variant === 'kpi'}`,
    `      <span class="skeleton__line skeleton__line--title"></span>`,
    `      <span class="skeleton__line skeleton__line--value"></span>`,
    `    {:else}`,
    `      {#each lineIndexes as line (line)}`,
    `        <span class="skeleton__line"></span>`,
    `      {/each}`,
    `    {/if}`,
    `  </div>`,
    `{/if}`,
    ``,
  ]);
}

function generateKpiCard(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    title = 'Metric',`,
    `    format = 'number' as 'number' | 'currency' | 'percent',`,
    `    value = 0,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    format?: 'number' | 'currency' | 'percent';`,
    `    value?: number;`,
    `  } = $props();`,
    ``,
    `  function formatValue(amount: number, style: 'number' | 'currency' | 'percent'): string {`,
    `    if (style === 'currency') {`,
    `      return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(amount);`,
    `    }`,
    `    if (style === 'percent') {`,
    `      return new Intl.NumberFormat(undefined, { style: 'percent', maximumFractionDigits: 1 }).format(`,
    `        amount / 100,`,
    `      );`,
    `    }`,
    `    return new Intl.NumberFormat().format(amount);`,
    `  }`,
    `</script>`,
    ``,
    `<article class="kpi-card" {id}>`,
    `  <h3>{title}</h3>`,
    `  <p class="kpi-value">{formatValue(value ?? 0, format ?? 'number')}</p>`,
    `</article>`,
    ``,
  ]);
}

function generateLineChart(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange, Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    title = 'Chart',`,
    `    xField = 'date',`,
    `    yField = 'value',`,
    `    data = [] as Row[],`,
    `    range,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    xField?: string;`,
    `    yField?: string;`,
    `    data?: Row[];`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const filtered = $derived(filterByRange(data, range));`,
    `  const points = $derived.by(() => {`,
    `    const max = Math.max(...filtered.map((row) => Number(row[yField] ?? 0)), 1);`,
    `    return filtered`,
    `      .map((row, index) => {`,
    `        const x = (index / Math.max(filtered.length - 1, 1)) * 300 + 10;`,
    `        const y = 110 - (Number(row[yField] ?? 0) / max) * 90;`,
    `        return \`\${x},\${y}\`;`,
    `      })`,
    `      .join(' ');`,
    `  });`,
    ``,
    `  function filterByRange(source: Row[], value?: DateRange): Row[] {`,
    `    if (!value) return source;`,
    `    return source.filter((row) => {`,
    `      const dateValue = String(row.date ?? row.createdAt ?? '');`,
    `      if (!dateValue) return true;`,
    `      return dateValue >= value.start && dateValue <= value.end;`,
    `    });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="chart-card" {id}>`,
    `  <h3>{title}</h3>`,
    `  <svg class="line-chart" viewBox="0 0 320 120" role="img" aria-label={title}>`,
    `    <polyline fill="none" stroke="currentColor" stroke-width="2" points={points} />`,
    `  </svg>`,
    `  <p class="chart-meta">{filtered.length} points · x={xField} · y={yField}</p>`,
    `</section>`,
    ``,
  ]);
}

function generateBarChart(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange, Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    title = 'Chart',`,
    `    data = [] as Row[],`,
    `    range,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    data?: Row[];`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const filtered = $derived(filterByRange(data, range));`,
    ``,
    `  function barHeight(row: Row): number {`,
    `    const max = Math.max(...filtered.map((entry) => Number(entry.value ?? 0)), 1);`,
    `    return (Number(row.value ?? 0) / max) * 100;`,
    `  }`,
    ``,
    `  function filterByRange(source: Row[], value?: DateRange): Row[] {`,
    `    if (!value) return source;`,
    `    return source.filter((row) => {`,
    `      const dateValue = String(row.date ?? row.createdAt ?? '');`,
    `      if (!dateValue) return true;`,
    `      return dateValue >= value.start && dateValue <= value.end;`,
    `    });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="chart-card" {id}>`,
    `  <h3>{title}</h3>`,
    `  <div class="bar-chart">`,
    `    {#each filtered as row, index (String(row.id ?? index))}`,
    `      <div`,
    `        class="bar"`,
    `        style:height="{barHeight(row)}%"`,
    `        title={String(row.label ?? row.id ?? index)}`,
    `      ></div>`,
    `    {/each}`,
    `  </div>`,
    `</section>`,
    ``,
  ]);
}

function generatePieChart(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { DateRange, Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    title = 'Chart',`,
    `    labelField = 'label',`,
    `    valueField = 'value',`,
    `    donut = false,`,
    `    data = [] as Row[],`,
    `    range,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    labelField?: string;`,
    `    valueField?: string;`,
    `    donut?: boolean;`,
    `    data?: Row[];`,
    `    range?: DateRange;`,
    `  } = $props();`,
    ``,
    `  const filtered = $derived(filterByRange(data, range));`,
    `  const colors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];`,
    ``,
    `  const gradient = $derived.by(() => {`,
    `    const total = filtered.reduce((sum, row) => sum + Number(row[valueField] ?? 0), 0) || 1;`,
    `    let cumulative = 0;`,
    `    const stops = filtered.map((row, index) => {`,
    `      const value = Number(row[valueField] ?? 0);`,
    `      const percent = (value / total) * 100;`,
    `      const start = cumulative;`,
    `      cumulative += percent;`,
    `      return \`\${colors[index % colors.length]} \${start}% \${cumulative}%\`;`,
    `    });`,
    `    return \`conic-gradient(\${stops.join(', ') || '#d1d5db 0 100%'})\`;`,
    `  });`,
    ``,
    `  function color(index: number): string {`,
    `    return colors[index % colors.length] ?? colors[0];`,
    `  }`,
    ``,
    `  function filterByRange(source: Row[], value?: DateRange): Row[] {`,
    `    if (!value) return source;`,
    `    return source.filter((row) => {`,
    `      const dateValue = String(row.date ?? row.createdAt ?? '');`,
    `      if (!dateValue) return true;`,
    `      return dateValue >= value.start && dateValue <= value.end;`,
    `    });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="chart-card" {id}>`,
    `  <h3>{title}</h3>`,
    `  <div`,
    `    class={donut ? 'pie-chart pie-chart--donut' : 'pie-chart'}`,
    `    style:background={gradient}`,
    `  ></div>`,
    `  <ul class="pie-chart__legend">`,
    `    {#each filtered as row, index (String(row.id ?? index))}`,
    `      <li>`,
    `        <span style:background={color(index)}></span>`,
    `        {String(row[labelField] ?? row.id ?? index)}`,
    `      </li>`,
    `    {/each}`,
    `  </ul>`,
    `</section>`,
    ``,
  ]);
}

function generateTimer(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import { onDestroy } from 'svelte';`,
    `  let {`,
    `    id,`,
    `    label = 'Timer',`,
    `    mode = 'interval' as 'interval' | 'countdown',`,
    `    intervalMs = 5000,`,
    `    durationMs = 30000,`,
    `    autoStart = true,`,
    `    value = $bindable(0),`,
    `  }: {`,
    `    id?: string;`,
    `    label?: string;`,
    `    mode?: 'interval' | 'countdown';`,
    `    intervalMs?: number;`,
    `    durationMs?: number;`,
    `    autoStart?: boolean;`,
    `    value?: number;`,
    `  } = $props();`,
    ``,
    `  let elapsed = $state(value);`,
    `  let remaining = $state(Math.max(1, Math.ceil(durationMs / 1000)));`,
    `  let handle: ReturnType<typeof setInterval> | undefined;`,
    ``,
    `  if (autoStart) {`,
    `    const stepMs = mode === 'countdown' ? 1000 : intervalMs;`,
    `    handle = setInterval(() => {`,
    `      elapsed += 1;`,
    `      value = elapsed;`,
    `      if (mode === 'countdown') {`,
    `        remaining = Math.max(0, remaining - 1);`,
    `      }`,
    `    }, stepMs);`,
    `  }`,
    ``,
    `  onDestroy(() => {`,
    `    if (handle) clearInterval(handle);`,
    `  });`,
    `</script>`,
    ``,
    `<section class="timer" {id}>`,
    `  <div class="timer__header">`,
    `    <span class="timer__label">{label}</span>`,
    `    <span class="timer__mode">{mode}</span>`,
    `  </div>`,
    `  <p class="timer__value">`,
    `    {mode === 'countdown' ? \`\${remaining}s remaining\` : \`\${elapsed} ticks\`}`,
    `  </p>`,
    `</section>`,
    ``,
  ]);
}

function generateSvgInline(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    sourceMode = 'inline',`,
    `    markup = '',`,
    `    url = '',`,
    `    assetPath = '',`,
    `    width = 120,`,
    `    height = 120,`,
    `    ariaLabel = 'SVG graphic',`,
    `    fillField = '',`,
    `    row,`,
    `  }: {`,
    `    id?: string;`,
    `    sourceMode?: 'inline' | 'url' | 'path';`,
    `    markup?: string;`,
    `    url?: string;`,
    `    assetPath?: string;`,
    `    width?: number;`,
    `    height?: number;`,
    `    ariaLabel?: string;`,
    `    fillField?: string;`,
    `    row?: Row;`,
    `  } = $props();`,
    `  const fillColor =`,
    `    fillField && row && row[fillField] !== undefined ? String(row[fillField]) : undefined;`,
    `</script>`,
    ``,
    `{#if sourceMode === 'url' && url}`,
    `  <figure class="svg-inline" style:width="{width}px" style:height="{height}px" aria-label={ariaLabel}>`,
    `    <img src={url} alt={ariaLabel} />`,
    `  </figure>`,
    `{:else if sourceMode === 'path' && assetPath}`,
    `  <figure class="svg-inline svg-inline--asset" style:width="{width}px" style:height="{height}px" aria-label={ariaLabel}>`,
    `    <p class="svg-inline__placeholder">Asset: {assetPath}</p>`,
    `  </figure>`,
    `{:else}`,
    `  <figure class="svg-inline" style:width="{width}px" style:height="{height}px" style:color={fillColor} aria-label={ariaLabel}>`,
    `    {@html markup}`,
    `  </figure>`,
    `{/if}`,
    ``,
  ]);
}

function generateSvgIcon(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    markup = '',`,
    `    size = 24,`,
    `    color = 'currentColor',`,
    `    title = 'Icon',`,
    `    ariaLabel = '',`,
    `    colorField = '',`,
    `    row,`,
    `  }: {`,
    `    id?: string;`,
    `    markup?: string;`,
    `    size?: number;`,
    `    color?: string;`,
    `    title?: string;`,
    `    ariaLabel?: string;`,
    `    colorField?: string;`,
    `    row?: Row;`,
    `  } = $props();`,
    `  const resolvedColor =`,
    `    colorField && row && row[colorField] !== undefined ? String(row[colorField]) : color;`,
    `</script>`,
    ``,
    `<span`,
    `  class="svg-icon"`,
    `  style:width="{size}px"`,
    `  style:height="{size}px"`,
    `  style:color={resolvedColor}`,
    `  {title}`,
    `  aria-label={ariaLabel || title}`,
    `>`,
    `  {@html markup}`,
    `</span>`,
    ``,
  ]);
}

function generateWasmAsset(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    modulePath = 'wasm/modules/example.wasm',`,
    `    gluePath = 'wasm/glue/example.js',`,
    `  }: { id?: string; modulePath?: string; gluePath?: string } = $props();`,
    `</script>`,
    ``,
    `<section class="wasm-asset" {id}>`,
    `  <span class="wasm-asset__badge">WASM</span>`,
    `  <code>{modulePath}</code>`,
    `  {#if gluePath}`,
    `    <span class="wasm-asset__glue">+ {gluePath}</span>`,
    `  {/if}`,
    `</section>`,
    ``,
  ]);
}

function generateWasmWorkerHost(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    moduleName = 'dash-wasm-worker',`,
    `    showStatus = true,`,
    `  }: { id?: string; moduleName?: string; showStatus?: boolean } = $props();`,
    `</script>`,
    ``,
    `<section class="wasm-worker" {id}>`,
    `  <header class="wasm-worker__header">`,
    `    <span>{moduleName}</span>`,
    `    <span class="wasm-worker__status">Worker host</span>`,
    `  </header>`,
    `  {#if showStatus}`,
    `    <p class="wasm-worker__hint">Bind a WASM asset ref to initialize.</p>`,
    `  {/if}`,
    `</section>`,
    ``,
  ]);
}

function generateWasmModule(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    entryExport = 'run',`,
    `    label = 'WASM Module',`,
    `  }: { id?: string; entryExport?: string; label?: string } = $props();`,
    `</script>`,
    ``,
    `<section class="wasm-module" {id}>`,
    `  <h3>{label}</h3>`,
    `  <p class="wasm-module__export"><code>{entryExport}()</code></p>`,
    `</section>`,
    ``,
  ]);
}

function generateRoleGate(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { Snippet } from 'svelte';`,
    `  import { getCurrentRole } from '../auth/current-role.svelte.ts';`,
    `  let {`,
    `    id,`,
    `    label = 'Protected section',`,
    `    allowedRoles = [] as string[],`,
    `    statusText = 'Visible',`,
    `    hiddenStatusText = 'Hidden for current role',`,
    `    children,`,
    `  }: {`,
    `    id?: string;`,
    `    label?: string;`,
    `    allowedRoles?: string[];`,
    `    statusText?: string;`,
    `    hiddenStatusText?: string;`,
    `    children?: Snippet;`,
    `  } = $props();`,
    ``,
    `  const role = getCurrentRole();`,
    `  const hasRoleContext = role !== undefined && role !== '';`,
    `  const visible = !hasRoleContext || allowedRoles.length === 0 || allowedRoles.includes(role);`,
    `</script>`,
    ``,
    `<section`,
    `  class="rd-role-gate {visible ? 'rd-role-gate--visible' : 'rd-role-gate--hidden'}"`,
    `  {id}`,
    `  data-testid="rd-role-gate"`,
    `>`,
    `  {#if label}`,
    `    <span class="rd-field__label">{label}</span>`,
    `  {/if}`,
    `  {#if visible}`,
    `    <p class="rd-role-gate__status" data-testid="rd-role-gate-visible">{statusText}</p>`,
    `    {#if children}`,
    `      {@render children()}`,
    `    {:else}`,
    `      <p>Protected content</p>`,
    `    {/if}`,
    `  {:else}`,
    `    <p class="rd-role-gate__status rd-role-gate__status--hidden" data-testid="rd-role-gate-hidden">`,
    `      {hiddenStatusText}`,
    `    </p>`,
    `  {/if}`,
    `</section>`,
    ``,
  ]);
}

function generatePersonInvite(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    title = 'Invite team member',`,
    `    emailPlaceholder = 'name@company.com',`,
    `    submitLabel = 'Send invite',`,
    `    onSubmit,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    emailPlaceholder?: string;`,
    `    submitLabel?: string;`,
    `    onSubmit?: (email: string) => void;`,
    `  } = $props();`,
    ``,
    `  let email = $state('');`,
    `</script>`,
    ``,
    `<section class="onboarding-step" {id}>`,
    `  <h3>{title}</h3>`,
    `  <label class="field">`,
    `    <input class="input" type="email" placeholder={emailPlaceholder} bind:value={email} />`,
    `  </label>`,
    `  <button type="button" class="button" onclick={() => onSubmit?.(email)}>`,
    `    {submitLabel}`,
    `  </button>`,
    `</section>`,
    ``,
  ]);
}

function generateRoleAssign(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    title = 'Assign role',`,
    `    confirmLabel = 'Confirm access',`,
    `    summaryLabel = 'Review access before confirming',`,
    `    roles = [] as Array<{ id: string; name: string }>,`,
    `    onConfirm,`,
    `  }: {`,
    `    id?: string;`,
    `    title?: string;`,
    `    confirmLabel?: string;`,
    `    summaryLabel?: string;`,
    `    roles?: Array<{ id: string; name: string }>;`,
    `    onConfirm?: (roleId: string) => void;`,
    `  } = $props();`,
    ``,
    `  let selectedRoleId = $state(roles[0]?.id ?? '');`,
    `</script>`,
    ``,
    `<section class="onboarding-step" {id}>`,
    `  <h3>{title}</h3>`,
    `  <p class="onboarding-step__summary">{summaryLabel}</p>`,
    `  <label class="field">`,
    `    <select class="input" bind:value={selectedRoleId}>`,
    `      {#each roles as role (role.id)}`,
    `        <option value={role.id}>{role.name}</option>`,
    `      {/each}`,
    `    </select>`,
    `  </label>`,
    `  <button type="button" class="button" onclick={() => onConfirm?.(selectedRoleId)}>`,
    `    {confirmLabel}`,
    `  </button>`,
    `</section>`,
    ``,
  ]);
}

function generateWasmMedia(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    operation = 'transcode',`,
    `    outputFormat = 'mp4',`,
    `    showProgress = true,`,
    `    label = 'Media transcode',`,
    `    progress = 0,`,
    `  }: {`,
    `    id?: string;`,
    `    operation?: string;`,
    `    outputFormat?: string;`,
    `    showProgress?: boolean;`,
    `    label?: string;`,
    `    progress?: number;`,
    `  } = $props();`,
    `</script>`,
    ``,
    `<section class="wasm-media" {id}>`,
    `  <header class="wasm-media__header">`,
    `    <h3>{label}</h3>`,
    `    <span>{operation} → {outputFormat}</span>`,
    `  </header>`,
    `  {#if showProgress}`,
    `    <div class="wasm-media__progress" role="progressbar" aria-valuenow={progress}>`,
    `      <span style:width="{progress}%"></span>`,
    `    </div>`,
    `  {/if}`,
    `</section>`,
    ``,
  ]);
}
