import { joinLines } from './utils';

/** Inlined into exported Svelte apps (mirrors @rosettadash/core media helpers). */
export function generateEquirectFilterHelperFile(): string {
  return joinLines([
    `export interface EquirectFlatCropOptions {`,
    `  cropX: number;`,
    `  cropY: number;`,
    `  cropWidth: number;`,
    `  cropHeight: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}`,
    ``,
    `export function buildEquirectFlatCropFilter(options: EquirectFlatCropOptions): string {`,
    `  const cropX = Math.max(0, Math.round(options.cropX));`,
    `  const cropY = Math.max(0, Math.round(options.cropY));`,
    `  const cropWidth = Math.max(2, Math.round(options.cropWidth));`,
    `  const cropHeight = Math.max(2, Math.round(options.cropHeight));`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return \`crop=\${cropWidth}:\${cropHeight}:\${cropX}:\${cropY},scale=\${outputWidth}:\${outputHeight}\`;`,
    `}`,
    ``,
    `export function buildEquirectRectilinearFilter(options: {`,
    `  yaw: number;`,
    `  pitch: number;`,
    `  roll?: number;`,
    `  horizontalFov: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}): string {`,
    `  const yaw = Number(options.yaw) || 0;`,
    `  const pitch = Number(options.pitch) || 0;`,
    `  const roll = Number(options.roll ?? 0) || 0;`,
    `  const horizontalFov = Math.max(1, Number(options.horizontalFov) || 90);`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return [`,
    `    \`v360=input=equirect:output=rectilinear:yaw=\${yaw}:pitch=\${pitch}:roll=\${roll}:d_fov=\${horizontalFov}\`,`,
    `    \`scale=\${outputWidth}:\${outputHeight}\`,`,
    `  ].join(',');`,
    `}`,
    ``,
    `export function buildEquirectExtractFilter(`,
    `  mode: 'flat-crop' | 'rectilinear',`,
    `  options: EquirectFlatCropOptions & {`,
    `    yaw?: number;`,
    `    pitch?: number;`,
    `    roll?: number;`,
    `    horizontalFov?: number;`,
    `  },`,
    `): string {`,
    `  if (mode === 'rectilinear') {`,
    `    return buildEquirectRectilinearFilter({`,
    `      yaw: options.yaw ?? 0,`,
    `      pitch: options.pitch ?? 0,`,
    `      roll: options.roll ?? 0,`,
    `      horizontalFov: options.horizontalFov ?? 90,`,
    `      outputWidth: options.outputWidth,`,
    `      outputHeight: options.outputHeight,`,
    `    });`,
    `  }`,
    `  return buildEquirectFlatCropFilter(options);`,
    `}`,
    ``,
  ]);
}

export function generateVideoSource(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    label = 'Video source',`,
    `    accept = 'video/*',`,
    `    url = '',`,
    `    sourceWidth = 4096,`,
    `    sourceHeight = 2048,`,
    `    captureBlob,`,
    `    onVideoFile,`,
    `    onMetadata,`,
    `  }: {`,
    `    id?: string;`,
    `    label?: string;`,
    `    accept?: string;`,
    `    url?: string;`,
    `    sourceWidth?: number;`,
    `    sourceHeight?: number;`,
    `    captureBlob?: Blob;`,
    `    onVideoFile?: (file: File) => void;`,
    `    onMetadata?: (row: Row) => void;`,
    `  } = $props();`,
    ``,
    `  let fileName = $state('');`,
    ``,
    `  function emitFile(file: File) {`,
    `    fileName = file.name;`,
    `    onVideoFile?.(file);`,
    `    onMetadata?.({`,
    `      name: file.name,`,
    `      sourceWidth,`,
    `      sourceHeight,`,
    `      size: file.size,`,
    `    });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="media-source" {id}>`,
    `  <header class="media-source__header">`,
    `    <h3>{label}</h3>`,
    `    <span>{sourceWidth}×{sourceHeight}</span>`,
    `  </header>`,
    `  <label class="media-source__upload">`,
    `    <input type="file" {accept} onchange={(event) => {`,
    `      const file = (event.currentTarget as HTMLInputElement).files?.[0];`,
    `      if (file) emitFile(file);`,
    `    }} />`,
    `    <span>{fileName || 'Choose video file'}</span>`,
    `  </label>`,
    `  {#if url}`,
    `    <p class="media-source__url">URL: {url}</p>`,
    `  {/if}`,
    `  {#if captureBlob}`,
    `    <p class="media-source__capture">Live capture attached</p>`,
    `  {/if}`,
    `</section>`,
    ``,
  ]);
}

export function generateEquirectViewport(): string {
  return joinLines([
    `<script lang="ts">`,
    `  import type { Row } from '../types';`,
    `  let {`,
    `    id,`,
    `    label = 'Equirect viewport',`,
    `    sourceWidth = 4096,`,
    `    sourceHeight = 2048,`,
    `    cropX = 1508,`,
    `    cropY = 664,`,
    `    cropWidth = 1080,`,
    `    cropHeight = 720,`,
    `    outputWidth = 720,`,
    `    outputHeight = 480,`,
    `    onCropRegion,`,
    `  }: {`,
    `    id?: string;`,
    `    label?: string;`,
    `    sourceWidth?: number;`,
    `    sourceHeight?: number;`,
    `    cropX?: number;`,
    `    cropY?: number;`,
    `    cropWidth?: number;`,
    `    cropHeight?: number;`,
    `    outputWidth?: number;`,
    `    outputHeight?: number;`,
    `    onCropRegion?: (region: Row) => void;`,
    `  } = $props();`,
    ``,
    `  const cropStyle = $derived({`,
    `    left: \`\${(cropX / sourceWidth) * 100}%\`,`,
    `    top: \`\${(cropY / sourceHeight) * 100}%\`,`,
    `    width: \`\${(cropWidth / sourceWidth) * 100}%\`,`,
    `    height: \`\${(cropHeight / sourceHeight) * 100}%\`,`,
    `  });`,
    ``,
    `  function emitRegion() {`,
    `    onCropRegion?.({ cropX, cropY, cropWidth, cropHeight, outputWidth, outputHeight });`,
    `  }`,
    `</script>`,
    ``,
    `<section class="media-viewport" {id}>`,
    `  <header class="media-viewport__header">`,
    `    <h3>{label}</h3>`,
    `    <button type="button" onclick={emitRegion}>Emit crop region</button>`,
    `  </header>`,
    `  <div class="media-viewport__frame">`,
    `    <div class="media-viewport__crop" style:left={cropStyle.left} style:top={cropStyle.top} style:width={cropStyle.width} style:height={cropStyle.height}></div>`,
    `  </div>`,
    `  <p class="media-viewport__meta">`,
    `    Crop {cropWidth}×{cropHeight} → Output {outputWidth}×{outputHeight}`,
    `  </p>`,
    `</section>`,
    ``,
  ]);
}

export function generateLiveCapture(): string {
  return joinLines([
    `<script lang="ts">`,
    `  let {`,
    `    id,`,
    `    label = 'Live capture',`,
    `    includeInExport = false,`,
    `    facingMode = 'environment',`,
    `    audio = true,`,
    `    onCaptureBlob,`,
    `    onPreviewUrl,`,
    `  }: {`,
    `    id?: string;`,
    `    label?: string;`,
    `    includeInExport?: boolean;`,
    `    facingMode?: 'user' | 'environment';`,
    `    audio?: boolean;`,
    `    onCaptureBlob?: (blob: Blob) => void;`,
    `    onPreviewUrl?: (url: string) => void;`,
    `  } = $props();`,
    ``,
    `  let videoEl = $state<HTMLVideoElement | null>(null);`,
    `  let active = $state(false);`,
    `  let stream = $state<MediaStream | null>(null);`,
    ``,
    `  $effect(() => {`,
    `    return () => {`,
    `      stream?.getTracks().forEach((track) => track.stop());`,
    `    };`,
    `  });`,
    ``,
    `  async function startCapture() {`,
    `    const nextStream = await navigator.mediaDevices.getUserMedia({`,
    `      video: { facingMode },`,
    `      audio,`,
    `    });`,
    `    stream = nextStream;`,
    `    if (videoEl) {`,
    `      videoEl.srcObject = nextStream;`,
    `      await videoEl.play();`,
    `    }`,
    `    active = true;`,
    `    onPreviewUrl?.('live');`,
    `  }`,
    `</script>`,
    ``,
    `{#if !includeInExport}`,
    `  <section class="media-capture media-capture--authoring" {id}>`,
    `    <p>{label} (authoring only — enable includeInExport for runtime capture)</p>`,
    `  </section>`,
    `{:else}`,
    `  <section class="media-capture" {id}>`,
    `    <header><h3>{label}</h3></header>`,
    `    <video bind:this={videoEl} class="media-capture__video" muted playsinline></video>`,
    `    <button type="button" onclick={() => void startCapture()}>`,
    `      {active ? 'Camera active' : 'Start camera'}`,
    `    </button>`,
    `  </section>`,
    `{/if}`,
    ``,
  ]);
}

export function generateWasmMediaEquirect(): string {
  return joinLines([
    `<script lang="ts">`,
    `  /** Requires: npm install @ffmpeg/ffmpeg @ffmpeg/util */`,
    `  import { FFmpeg } from '@ffmpeg/ffmpeg';`,
    `  import { fetchFile, toBlobURL } from '@ffmpeg/util';`,
    `  import type { Row } from '../types';`,
    `  import { buildEquirectExtractFilter } from '../media/equirect-filter';`,
    ``,
    `  let {`,
    `    id,`,
    `    label = 'Media transcode',`,
    `    operation = 'transcode',`,
    `    extractionMode = 'flat-crop',`,
    `    outputFormat = 'mp4',`,
    `    cropX = 1508,`,
    `    cropY = 664,`,
    `    cropWidth = 1080,`,
    `    cropHeight = 720,`,
    `    outputWidth = 720,`,
    `    outputHeight = 480,`,
    `    yaw = 0,`,
    `    pitch = 0,`,
    `    horizontalFov = 90,`,
    `    showProgress = true,`,
    `    inputFile,`,
    `    cropRegion,`,
    `    onOutputBlob,`,
    `    onProgress,`,
    `    onMetadata,`,
    `  }: {`,
    `    id?: string;`,
    `    label?: string;`,
    `    operation?: string;`,
    `    extractionMode?: 'flat-crop' | 'rectilinear';`,
    `    outputFormat?: string;`,
    `    cropX?: number;`,
    `    cropY?: number;`,
    `    cropWidth?: number;`,
    `    cropHeight?: number;`,
    `    outputWidth?: number;`,
    `    outputHeight?: number;`,
    `    yaw?: number;`,
    `    pitch?: number;`,
    `    horizontalFov?: number;`,
    `    showProgress?: boolean;`,
    `    inputFile?: File | Blob;`,
    `    cropRegion?: Row;`,
    `    onOutputBlob?: (blob: Blob) => void;`,
    `    onProgress?: (value: number) => void;`,
    `    onMetadata?: (rows: Row[]) => void;`,
    `  } = $props();`,
    ``,
    `  let ffmpeg = $state<FFmpeg | null>(null);`,
    `  let progress = $state(0);`,
    `  let busy = $state(false);`,
    `  let error = $state<string | null>(null);`,
    ``,
    `  function resolveCrop() {`,
    `    return {`,
    `      cropX: Number(cropRegion?.cropX ?? cropX),`,
    `      cropY: Number(cropRegion?.cropY ?? cropY),`,
    `      cropWidth: Number(cropRegion?.cropWidth ?? cropWidth),`,
    `      cropHeight: Number(cropRegion?.cropHeight ?? cropHeight),`,
    `      outputWidth: Number(cropRegion?.outputWidth ?? outputWidth),`,
    `      outputHeight: Number(cropRegion?.outputHeight ?? outputHeight),`,
    `    };`,
    `  }`,
    ``,
    `  async function ensureFfmpeg() {`,
    `    if (ffmpeg) return ffmpeg;`,
    `    const instance = new FFmpeg();`,
    `    instance.on('progress', ({ progress: ratio }) => {`,
    `      const next = Math.round(ratio * 100);`,
    `      progress = next;`,
    `      onProgress?.(next);`,
    `    });`,
    `    const baseURL = 'https://unpkg.com/@ffmpeg/core@0.12.6/dist/umd';`,
    `    await instance.load({`,
    `      coreURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.js\`, 'text/javascript'),`,
    `      wasmURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.wasm\`, 'application/wasm'),`,
    `    });`,
    `    ffmpeg = instance;`,
    `    return instance;`,
    `  }`,
    ``,
    `  async function runEquirectExtract() {`,
    `    if (!inputFile) {`,
    `      error = 'Attach a video file before extracting.';`,
    `      return;`,
    `    }`,
    `    busy = true;`,
    `    error = null;`,
    `    try {`,
    `      const instance = await ensureFfmpeg();`,
    `      const inputName = 'input.mp4';`,
    `      const outputName = \`output.\${outputFormat}\`;`,
    `      await instance.writeFile(inputName, await fetchFile(inputFile));`,
    `      const crop = resolveCrop();`,
    `      const filter = buildEquirectExtractFilter(extractionMode, {`,
    `        ...crop,`,
    `        yaw,`,
    `        pitch,`,
    `        horizontalFov,`,
    `      });`,
    `      await instance.exec(['-i', inputName, '-vf', filter, '-c:a', 'copy', outputName]);`,
    `      const data = await instance.readFile(outputName);`,
    `      const blob = new Blob([data], { type: \`video/\${outputFormat}\` });`,
    `      onOutputBlob?.(blob);`,
    `      onMetadata?.([{`,
    `        filter,`,
    `        outputWidth: crop.outputWidth,`,
    `        outputHeight: crop.outputHeight,`,
    `        format: outputFormat,`,
    `      }]);`,
    `    } catch (nextError) {`,
    `      error = nextError instanceof Error ? nextError.message : 'Extract failed';`,
    `    } finally {`,
    `      busy = false;`,
    `    }`,
    `  }`,
    ``,
    `  const filterPreview = $derived(`,
    `    operation === 'equirect-extract'`,
    `      ? buildEquirectExtractFilter(extractionMode, {`,
    `          ...resolveCrop(),`,
    `          yaw,`,
    `          pitch,`,
    `          horizontalFov,`,
    `        })`,
    `      : '',`,
    `  );`,
    `</script>`,
    ``,
    `<section class="wasm-media" {id}>`,
    `  <header class="wasm-media__header">`,
    `    <h3>{label}</h3>`,
    `    <span>{operation} → {outputFormat}</span>`,
    `  </header>`,
    `  {#if filterPreview}`,
    `    <code class="wasm-media__filter">{filterPreview}</code>`,
    `  {/if}`,
    `  {#if showProgress}`,
    `    <div class="wasm-media__progress" role="progressbar" aria-valuenow={progress}>`,
    `      <span style:width="{progress}%"></span>`,
    `    </div>`,
    `  {/if}`,
    `  {#if operation === 'equirect-extract'}`,
    `    <button type="button" disabled={busy || !inputFile} onclick={() => void runEquirectExtract()}>`,
    `      {busy ? 'Extracting…' : 'Extract subsection'}`,
    `    </button>`,
    `  {:else}`,
    `    <p class="wasm-media__hint">Wire input file and choose equirect-extract operation.</p>`,
    `  {/if}`,
    `  {#if error}`,
    `    <p class="wasm-media__error">{error}</p>`,
    `  {/if}`,
    `</section>`,
    ``,
  ]);
}
